### ISSUE TITLE
[BUG]wiki里有一些不太一致的地方

### ISSUE THREAD

**Issue by christaikobo** [IrineSistiana/mosdns#107]
也许有点儿吹毛求疵，wiki里几个页面有一些不太一致的地方

比如域名匹配器匹配外部文件（ext:.....），有时候外面包了双引号，有时候是单引号，有时候又没有引号
自己试了以下，似乎是不需要加引号的

plugin页面绝大多数例子都是用双引号，少数单引号
但是configuration页面全部都是单引号

yaml好像单引号和双引号有些地方还是不一样的吧，如果统一一下可能更不容易造成误解

**Comment by muziling** [comment]
forward 的wiki说明：参数和运行行为跟 AdguardHome 是一样的。 mosdns有配置项insecure_skip_verify， fastest_ip 我去看了 AdguardTeam/dnsproxy的运行参数，并没有这两个配置项或者名字不一样， 具体是怎么对应的？  看了代码，应该是只支持wiki里举例的几个参数

**Comment by christaikobo** [comment]
作者似乎全部改成单引号了。感谢！
