### ISSUE TITLE
[Feature request] 关于细化log 输出格式的建议

### ISSUE THREAD

**Issue by kuyagic** [IrineSistiana/mosdns#11]
**希望添加的功能**

有时候在局域网中 会需要查询 来自某些个固定IP 的dns 请求. 目前的考虑是 是否
1. 在每个插件里 指定是否这个插件的运行过程和结果单独记录日志 并指定前缀,可以适当省略 日志来源的源文件 信息(比如多少行).
2. 在log 的插件内指定某些条件组合 输出 需要的内容 包括不限于 查询来源IP, 查询类型, 查询内容, 处理的插件,返回的结果之类的. 也是可以省略很多 堆栈信息. 直接输出需要的内容

**Comment by IrineSistiana** [comment]
不想搞这么复杂， debug 日志能看就行。

格式化日志输出是 DNS 服务器的功能。mosdns 是转发器。

**Comment by christaikobo** [comment]
有一个变通方法，单独开一个mosdns的实例放在别的端口上，用iptables把源IP的dns请求全部转发到该端口上，这样日志就只记录这个客户端的请求了

**Comment by IrineSistiana** [comment]
为啥要记录客户端的请求？🤔

**Comment by christaikobo** [comment]
他是干啥的我不知道
我有次想对几个域名单独debug，如果直接在现有的mosdns上开debug，内网的电脑NAS手机PAD加一起的DNS请求刷屏太严重了
后来单独开了一个端口专门做这个
如果有个单独debug模式会方便些，比如
`./mosdns -c config.yaml -dir2exe -debug "www.example.com"`可以输出该域名在路由和pipeline里面的走向和结果
当然现在这个办法也可以用

**Comment by IrineSistiana** [comment]
debug 的时候我是用 `grep`，感觉还行。
