### ISSUE TITLE
希望能实现，最快IP地址和域名预查询功能。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [IrineSistiana/mosdns#119]
**希望添加的功能**
smartdns 上的特殊功能 
最快IP地址：
对上游返回的多个IP进行测速，对客户端返回最优的结果

域名预查询： 
对缓存或指定的域名解析，在 TTL 时间，快要到期时，向上游查询，更新解析结果。 
保证客户端最小的查询延迟。

**Comment by IrineSistiana** [comment]
最快IP。这功能早就有了。
缓存预取。太复杂不想实现。建议套娃。

**Comment by wy16W2pIilK1xgqN** [comment]
> 最快IP。这功能早就有了。
> 缓存预取。太复杂不想实现。建议套娃。

 最快IP是这个吗？`fastest_ip `
之前还以为是上游 DNS 的最快响应。
😂

谢谢回复。

**Comment by IrineSistiana** [comment]
是。emm wiki 没写清楚确实会有歧义。
个人感受 unbound的预取体验比smartdns好
