### ISSUE TITLE
win10安装

### ISSUE THREAD

**Issue by Yumega** [IrineSistiana/mosdns#128]
**出现了什么问题**
win10按照要求安装后，在yogaDNS找不到mosdns选项啊

描述一下问题的表现。可以直接附上截图或log。建议附`debug`级别的log。

```txt

```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：

mosdns -v1.8.4

使用的启动参数或启动方式：

操作系统和平台：win10

进行了什么操作导致了问题的出现：

使用的配置文件：

```yaml

````

**Comment by chinaniupai** [comment]
@lrinesistiana 是这样的

**Comment by chinaniupai** [comment]
@IrineSistiana 是这样的
