### ISSUE TITLE
[Feature request] Respond with an empty answer to all AAAA requests

### ISSUE THREAD

**Issue by sammimk830** [IrineSistiana/mosdns#129]
**希望添加的功能**

由于现时技术问题，好多时只能用ip v4才能访问，所以想有个功能系只返回ip v4的，就是AdGuardHome里的aaaa_disabled功能一样，谢谢！

**Comment by IrineSistiana** [comment]
有这功能。blackhole。配合 if 还可以选择性屏蔽。

aaaa_disabled 只能全屏蔽。
