### ISSUE TITLE
如何设置能够实现访问远端服务器时的Failover

### ISSUE THREAD

**Issue by cutemanworking** [IrineSistiana/mosdns#133]
我通过本地几个socks5代理访问远端的DNS服务器，但发现当第一个设定的代理服务器失效导致不能访问远端时，剩下的好像就不起效了。 如果才能实现第一个失效时按顺序或并发访问其它的服务器？ 

plugin:
  - tag: proxy_remote
    type: fast_forward
    args:
      deduplicate: true    
      upstream:            
        - protocol: tcp     
          addr: 8.8.8.8:53  
          timeout: 5          
          idle_timeout: 10    
          socks5: "127.0.0.1:1989"
        - protocol: tcp    
          addr: 1.1.1.1:53  
          timeout: 5         
          idle_timeout: 10    
          socks5: "127.0.0.1:1984"  
        - protocol: udp   
          addr: 127.0.0.1:2053 
          timeout: 5         
          idle_timeout: 10

**Comment by IrineSistiana** [comment]
> 第一个设定的代理服务器失效导致不能访问远端时，剩下的好像就不起效了。 

如果配置了多个服务器，会并发请求是所有服务器。不应该出现这种现象。
你看看debug 日志。
