### ISSUE TITLE
[Feature request]在wiki中添加有关UDP Receive Buffer Size的内容

### ISSUE THREAD

**Issue by brainos233** [IrineSistiana/mosdns#147]
使用DoQ时，会出现`failed to sufficiently increase receive buffer size (was: 120 kiB, wanted: 2048 kiB, got: 240 kiB)`的错误。
有sysctl的情况下，用
`sysctl -w net.core.rmem_max=2500000`
没有sysctl，用
`echo 2500000 > /proc/sys/net/core/rmem_max`来解决。

**Comment by IrineSistiana** [comment]
已加入 wiki，thanks
