### ISSUE TITLE
[Feature request] 能添加测速功能并能域名绑定DNS么？

### ISSUE THREAD

**Issue by bigfoxtail** [IrineSistiana/mosdns#150]
能添加测速功能么，并能域名绑定DNS？我不知道这个功能添加进去复杂不复杂，会不会有其他的问题，
故有此一问，希望有人能解答下。
从多个DNS获取到IP后，存储多个DNS返回的相关IP，对ip进行基本的测速，返回最快的ip，
或者按默认规则返回ip，同时对IP进行存储。
后台对相关的IP进行tcp测速，或者HTTP测速，（或者进一步判断网站返回的内容是否正常。。。），
然后缓存正常而且速度快的IP地址，对域名进行统计，对经常访问的域名后台定时刷新缓存，
且域名默认用之前返回最快的DNS进行解析。
。。。。。。。。我这奇葩需求是不是太过分了？。。

**Comment by IrineSistiana** [comment]
forward 插件有基本的tcp测速。其他方式暂不考虑。
