### ISSUE TITLE
[Feature request] 实现与 `dnscrypt-proxy` 项目相同的 HOSTS 语法

### ISSUE THREAD

**Issue by IceCodeNew** [IrineSistiana/mosdns#16]
**希望添加的功能**

我稍微深挖了一下这个项目的所有内置插件，非常实用。其中匹配器插件 `hosts` 的语法我仔细看了一下和 https://github.com/DNSCrypt/dnscrypt-proxy 项目的 `Cloaking` 语法非常相似（这里的 `Cloaking` 基本就是 `hosts` 插件实现的功能）
我这里把所有 Cloaking 的语法细节列出来，与 `hosts` 插件一致的会用对勾标记：
- [x] 域名在前，IP 在后
- [x] 一条域名后面可以指定多个 IP
- [x] 多行出现的相同域名不会覆盖，而是被合并
- [x] 支持 IPv6
  - [x] （不使用方括号包裹 IPv6 地址）
- [ ] 支持以域名作为某一条目的别名（即对 `a.b.c` 域名的查询返回 `d.e.f` 的结果）
- [ ] 支持通配符
  - [ ] 值得注意的语法差异：不加修饰符，单纯域名在 `hosts` 插件中只匹配完整域名；但在 https://github.com/DNSCrypt/dnscrypt-proxy 项目中还匹配这一级域名下的所有子域名。

个人希望 mosdns 项目的 `hosts` 插件语法可以做到和 https://github.com/DNSCrypt/dnscrypt-proxy 项目一致，这样可以更方便地分享已有的 hosts 文件成果。而且支持通配符匹配也确实会大大增强 `hosts` 插件的能力。

---

附：
[Cloaking 语法官方 Wiki 说明](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Cloaking)

**Comment by IrineSistiana** [comment]
mosdns 的 hosts 语法参考了 Cloaking。

因为目前的唯一路由插件 sequence 不支持这种 rewrite 操作。所以最后两条这种高级功能没实现。

所以需要新的路由插件。目前想要的功能有点少，不好决定。可能要一段时间。

BTW, 我对 dnscrypt-proxy 最后那个 "还匹配这一级域名下的所有子域名" 的特性有异议，所以不打算实现。

**Comment by IrineSistiana** [comment]
hosts 现在用的也是 domain_matcher 的匹配器。和 v2ray 匹配规则一样。~v2ray 大法好~
关于 `支持以域名作为某一条目的别名（即对 a.b.c 域名的查询返回 d.e.f 的结果`，目前没发现使用场景。所以还不打算加。
感谢反馈。
