### ISSUE TITLE
[Feature request]能否给fast_forward插件也安排上fastest_ip检测

### ISSUE THREAD

**Issue by QiuSimons** [IrineSistiana/mosdns#165]
需求如题

需要解决这样一个问题，forward插件自带的fastest_ip几乎没有可选参数，会导致必须等待所有上游返回结果后才能继续。
希望fast_forward插件能实现一个fastest_ip检测，当第一个上游返回结果后，等待 xx ms后，立即开始对所有已知结果进行测速（忽略其他未返回结果的上游），测速完成后，可选保留测速结果最快的前 x 个解析结果。
这样既可以避免测速流程过长的问题，又能满足部分软件需要多个ip解析结果，进行多连接下载加速的需求。

**Comment by IrineSistiana** [comment]
无计划。~个人经验: fastest_ip 测速看上去很好很有道理但是实际上根本不中用。不如选个好上游。其他测速方式一样。~

**Comment by QiuSimons** [comment]
> 无计划。~个人经验: fastest_ip 测速看上去很好很有道理但是实际上根本不中用。不如选个好上游。其他测速方式一样。~
明白了，感谢回复~
