### ISSUE TITLE
[2.0] 关于新版本

### ISSUE THREAD

**Issue by IrineSistiana** [IrineSistiana/mosdns#166]
计划近期更新 mosdns v2.0

当然，v2 和 v1 版本部分配置不兼容。所以直接更新可能会遇到问题。如遇问题，参考报错找到不兼容的插件，然后参照最新的 wiki 更新配置。

目前的变化有 (master 分支):

---

新玩意:

- `cache` 支持 lazy cache。
- 新预定义插件 `_single_flight`，去除重复的请求。(原为 `fast_forward` 的 `deduplicate` 功能，现独立成插件。)

---

配置文件不兼容的变更:

- `ipset`: 修改 ttl 的设置已移除。(在 `v1.3` 已被 `ttl` 替代)
- `fast_forward`: 不再支持 `v1.7` 版本以前的老地址格式。(已和 `forward` (也就是 adhome) 统一)
- 移除上古独立插件 `fallback` 和 `parallel`。( `v1.0` 以前已整合进 `执行序列`)
- `cache`: 移除 `cleaner_interval` 设置。(很少使用并且和 lazy cache 不兼容)
- `forward/fast_forward`: 移除 `deduplicate` 设置。

行为变化:

- 执行序列中的 `if` 和 `if_and` 现在只生效一个。优先 `if`。
- `cache` redis 后端的存储格式有变化，更新需清除 redis 缓存。

插件 API:

- **插件接口 `dispatcher/handler`  变化**。简化接口。现在插件可以控制如何执行后续插件。能更简单的实现像 cache rewrite 这类需要运行两次(处理请求后还要处理应答)的插件。原有插件需实现新接口。

**Comment by QiuSimons** [comment]
使用的配置文件：https://github.com/QiuSimons/openwrt-mos/blob/903e987/luci-app-mosdns/files/mosdns/config.yaml
mosdns版本： 2.0.0 alpha2
遇到的问题：无法正确过滤AAAA解析结果（去掉序列里的lazy_cache，同样的配置文件再1.8.7上能正确过滤AAAA解析结果）

**Comment by IrineSistiana** [comment]
> 使用的配置文件：https://github.com/QiuSimons/openwrt-mos/blob/903e987/luci-app-mosdns/files/mosdns/config.yaml
> mosdns版本： 2.0.0 alpha2
> 遇到的问题：无法正确过滤AAAA解析结果（去掉序列里的lazy_cache，同样的配置文件再1.8.7上能正确过滤AAAA解析结果）

看样子你是想过滤某些域名的 AAAA，能举个具体的域名么。我简单试了试没发现问题。

**Comment by QiuSimons** [comment]
我测试的是www.youtube.com
稍后我开debug模式看一下

**Comment by IrineSistiana** [comment]
发现了，有 bug。

**Comment by IrineSistiana** [comment]
试试 d91fa92

**Comment by QiuSimons** [comment]
> 试试 [d91fa92](https://github.com/IrineSistiana/mosdns/commit/d91fa92b7f443bb2129356443e9ba8fdac302f49)

有aarch64_linux的预编译二进制么？我吃完饭替换测试下

**Comment by IrineSistiana** [comment]
> > 试试 [d91fa92](https://github.com/IrineSistiana/mosdns/commit/d91fa92b7f443bb2129356443e9ba8fdac302f49)
> 
> 有aarch64_linux的预编译二进制么？我吃完饭替换测试下

没有，但你可以 `python release.py`。基本上任何平台都可以，只要有 python 和 golang。

**Comment by QiuSimons** [comment]
> > > 试试 [d91fa92](https://github.com/IrineSistiana/mosdns/commit/d91fa92b7f443bb2129356443e9ba8fdac302f49)
> > 
> > 
> > 有aarch64_linux的预编译二进制么？我吃完饭替换测试下
> 
> 没有，但你可以 `python release.py`。基本上任何平台都可以，只要有 python 和 golang。

好的稍后我自行编译测试哈

**Comment by QiuSimons** [comment]
> > > 试试 [d91fa92](https://github.com/IrineSistiana/mosdns/commit/d91fa92b7f443bb2129356443e9ba8fdac302f49)
> > 
> > 
> > 有aarch64_linux的预编译二进制么？我吃完饭替换测试下
> 
> 没有，但你可以 `python release.py`。基本上任何平台都可以，只要有 python 和 golang。

测试功能正常（是不是可以release个alpha3？）

**Comment by IrineSistiana** [comment]
> > > > 试试 [d91fa92](https://github.com/IrineSistiana/mosdns/commit/d91fa92b7f443bb2129356443e9ba8fdac302f49)
> > > 
> > > 
> > > 有aarch64_linux的预编译二进制么？我吃完饭替换测试下
> > 
> > 
> > 没有，但你可以 `python release.py`。基本上任何平台都可以，只要有 python 和 golang。
> 
> 测试功能正常（是不是可以release个alpha3？）

不急，先试用几天。

**Comment by QiuSimons** [comment]
> * 新插件 `single_flight`，去除重复的请求。(原为 `fast_forward` 的 `deduplicate` 功能，现独立成插件。)

single_flight有什么模版或者文档么😉

**Comment by IrineSistiana** [comment]
> > * 新插件 `single_flight`，去除重复的请求。(原为 `fast_forward` 的 `deduplicate` 功能，现独立成插件。)
> 
> single_flight有什么模版或者文档么😉

就一个预定义插件。`_single_flight`。不需要配置直接用。这个插件后面的就会被自动去重。

**Comment by QiuSimons** [comment]
> > > * 新插件 `single_flight`，去除重复的请求。(原为 `fast_forward` 的 `deduplicate` 功能，现独立成插件。)
> > 
> > 
> > single_flight有什么模版或者文档么😉
> 
> 就一个预定义插件。`_single_flight`。不需要配置直接用。这个插件后面的就会被自动去重。

好的，我试试看

**Comment by linusxiong** [comment]
_single_flight是放在转发到上游之前还是放在一开始呢

**Comment by IrineSistiana** [comment]
> _single_flight是放在转发到上游之前还是放在一开始呢

看需求。都行。
