### ISSUE TITLE
[Feature request] SO_MARK 功能

### ISSUE THREAD

**Issue by akafeng** [IrineSistiana/mosdns#171]
看到 [README](https://github.com/IrineSistiana/mosdns/blob/main/README.md) 中使用了部分 V2ray 的源代码，能否移植一下 [SO_MARK](https://www.v2fly.org/config/transport.html#sockoptobject) 功能呢？
该功能可在多出口的网络环境，如专线、SD-WAN 等情况下，可通过策略路由等方式指定可访问 DNS 的对应出口，有效保障了 DNS 访问。
可以考虑在「forward」插件下实现这一特性，增加一项参数用于指定该值。
非常感谢。

**Comment by IrineSistiana** [comment]
done
