### ISSUE TITLE
[BUG]域名匹配器，是否支持泛域名匹配呢？

### ISSUE THREAD

**Issue by ilanni2460** [IrineSistiana/mosdns#183]
我们这边要匹配泛域名，不知道是否支持。规则我是这样写的：
  # 匹配阿里云域名插件
  - tag: query_has_aliyun_domain
    type: query_matcher
    args:
      domain:                # 匹配请求的域名
        - regexp: *\.oss-cn-hzjbp-b-internal\.aliyuncs\.com

**Comment by IrineSistiana** [comment]
不支持*号泛域名。需要写成正则的形式。

但是你这个例子用默认的 domain 匹配就好了。

`oss-cn-hzjbp-b-internal.aliyuncs.com`

**Comment by ilanni2460** [comment]
@IrineSistiana 我这个域名其实还有子域名呢，
比如a.oss-cn-hzjbp-b-internal.aliyuncs.com
b.oss-cn-hzjbp-b-internal.aliyuncs.com等

**Comment by IrineSistiana** [comment]
domian 会匹配子域名。
见 wiki。

**Comment by ilanni2460** [comment]
@IrineSistiana 好的，感谢😊
