### ISSUE TITLE
[Feature request] query_matcher 对请求中的ECS地址进行匹配

### ISSUE THREAD

**Issue by AeolusC** [IrineSistiana/mosdns#189]
**希望添加的功能**
query_matcher 对请求中的ECS地址进行匹配

本地主机(mosdns所在服务器)A
远程主机B 
DNS均为支持ecs的DNS，国外ECS DNS使用代理访问。场景使用了套娃或者转发，远程主机使用来到mosdns的请求客户端ip永远是内网ip，导致无法分清查询的客户端来源，所以只能从ECS带上客户端IP，所以会出现下述问题：
如果主机B原请求带了ecs的话，则返回结果符合主机B的最优结果。但主机A的查询因为要保证主机B ECS不变所以不能使用ecs插件覆盖ecs的ip。这个导致主机A的查询使用代理的DNS返回的则是代理IP的最优结果，只有没使用代理的DNS查询是主机A最优结果。

如果有这个功能，则可以判断ECS中的地址是否为内网IP来决定是否用ecs插件来覆盖原ecs内容。使场景2主机A和主机B都可以实现最佳结果。

**Comment by LittleGrocery** [comment]
看了好几次 还是不太懂你搞这么复杂到底为了实现什么功能 所以主机A和主机B都是云服务器是吗？因为他们都是一个服务商的所以都在一个内网？主机B的作用是什么 如果是为了获取无污染结果的话哪个主机是架设的海外的？看得我懵

**Comment by AeolusC** [comment]
> 看了好几次 还是不太懂你搞这么复杂到底为了实现什么功能 所以主机A和主机B都是云服务器是吗？因为他们都是一个服务商的所以都在一个内网？主机B的作用是什么 如果是为了获取无污染结果的话哪个主机是架设的海外的？看得我懵

就是本地和外地机器共用一个DNS服务，DNS建在本地，部分DNS走的代理（绝大部分国外DOH DOT都直连不上），所以需要每个请求带上ECS来获得最好结果。
如果没有外地机器，则可以直接所有请求都强行用本地IP段的ecs覆盖，代理就不会影响结果准确。
但有了外地机器，即便客户端不同，但因为转发和套娃，所以请求发到mosdns时客户端IP都是内网IP。现有query_match在客户端IP都为内网转发时难以判断原请求的来源，决定不了”用新的ECS覆盖原请求ECS“还是”保留原请求的ecs“。
所以想query_match加上对ecs中地址段的匹配。

**Comment by LittleGrocery** [comment]
我好像有点懂了 
你意思是不是说 A机器使用mosdns分流 海外域名通过代理请求 大陆域名一律使用运营商解析结果 B机器的话通过请求A机器的DNS服务联网 但是你不想在A机器架设DNS分流 对于A机器cdn友好的大陆域名解析结果  却对B机器不友好  是这意思吧

那我有个办法 A机器请求本地的mosdns时候它的ip其实是127.0.0.1  但是B机器请求A机器时候ip一定是内网ip 肯定不是本地地址 你只需要用query_matcher的client_ip即可进行分流 来源是本机的就返回A友好的ip 是内网地址就返回B友好的

**Comment by AeolusC** [comment]
> 我好像有点懂了 你意思是不是说 A机器使用mosdns分流 海外域名通过代理请求 大陆域名一律使用运营商解析结果 B机器的话通过请求A机器的DNS服务联网 但是你不想在A机器架设DNS分流 对于A机器cdn友好的大陆域名解析结果 却对B机器不友好 是这意思吧

对 差不多就这个意思

> 那我有个办法 A机器请求本地的mosdns时候它的ip其实是127.0.0.1 但是B机器请求A机器时候ip一定是内网ip 肯定不是本地地址 你只需要用query_matcher的client_ip即可进行分流 来源是本机的就返回A友好的ip 是内网地址就返回B友好的

因为下游套了个AGH做广告过滤和自定义host，相对mosdns有UI处理更快捷，而且可以自动更新规则，A 、B的请求经过了这里再转发给mosdns的，所以进来的IP都是同一个，都是AGH的。现在我只能妥协下。B本地也建立一个下游AGH，然后直接远程mosdns不要AGH做统一中转了，这样两个的client_ip获取到B的就是公网的，获取到A的就是内网的，这样暂时OK了。但如果能判断ECS就是更完美的解决方案咯。

`  - tag: 'main_sequence'
    type: 'sequence'
    args:
      exec:
        - 'init_ecs'                    # 初始化ECS
        - 'mem_cache'                   # 启用缓存
        - if:
            - 'query_is_cn_domain'      # 已知的本地域名
            - '!_query_is_common'       # 和不常见的请求类型
          exec:
            - 'cn_parallel'             # 用本地服务器
            - '_end'
        - if:
            - 'query_is_non_cn_domain'  # 已知的非本地域名
          exec:
            - 'forward_remote_edns'     # 用远程服务器
            - '_end'
        - 'default_parallel'            # 剩下的未知域名用 IP 分流。
  - tag: 'cn_parallel'
    type: 'sequence'
    args:
      exec:
        - parallel:
            - - 'forward_dnspod'                    
              - if:
                  - 'query_is_ali_domain'           
                  - 'response_has_ali_domain'       
                exec:
                  - '_drop_response'
            - - 'forward_alidns' 
              - if:
                  - 'query_is_tx_domain'  
                  - 'response_has_tx_domain'        
                exec:
                  - '_drop_response'
          timeout: 0
  - tag: 'default_parallel'
    type: 'sequence'
    args:
      exec:
        - parallel:
            - - 'forward_cn_edns' 
              - if:
                  - '!response_has_cn_ip'
                exec:
                  - '_drop_response'
            - - 'forward_remote_edns' 
          timeout: 0
  - tag: 'init_ecs'
     #处理ECS
    type: 'sequence'
    args:
      exec:
        - 'auto_ecs'                    # 自动ECS
        - if:
            - 'query_is_from_lan'       # 请求客户端来自于本地
          exec:
            - 'force_ecs'               # 覆盖ECS
  - tag: 'auto_ecs'
    type: 'ecs'
    args:
      auto: true
      force_overwrite: false
      mask4: 24
      mask6: 48
      ipv4: ''
      ipv6: ''
  - tag: 'force_ecs'
    type: 'ecs'
    args:
      auto: false
      force_overwrite: true
      mask4: 24
      mask6: 48
      ipv4: '$主机A IPV4'
      ipv6: '$主机A IPV6'
`

**Comment by IrineSistiana** [comment]
这个功能实现不了。牵涉到IP段匹配IP段。
