### ISSUE TITLE
[Feature request]希望添加对timeout的结果重定向至另一组dns解析

### ISSUE THREAD

**Issue by yaott2020-666** [IrineSistiana/mosdns#190]
**希望添加的功能**

当一组dns全部失效时，可以重定向至另一组dns组解析，而不是返回错误

在wiki里面没有找到对应配置（wiki的type介绍貌似不全，有一些type是从其他地方知道的）

**Comment by IrineSistiana** [comment]
wiki 搜 `fallback`

**Comment by yaott2020-666** [comment]
@IrineSistiana  可以只对指定域名使用fallback吗，具体如何配置，Wiki中没有对应范例

**Comment by yaott2020-666** [comment]
还有就是“请求失败（timeout）”有没有对应插件可以体现（在Wiki里没有找到），这样可以使用if进行分流，可以不需要fallback
