### ISSUE TITLE
希望能命名 mosdns

### ISSUE THREAD

**Issue by cresky-github** [IrineSistiana/mosdns#191]
![image](https://user-images.githubusercontent.com/52242290/139749631-60f637bc-5554-458f-9d7b-99287cf87076.png)
看到  UnKnown  就是不爽，能改成自己喜欢的文字吗？

**Comment by realconnor** [comment]
`10.0.0.48`是局域网机器？
在mosdns配置里改hosts应该可以，或者把局域网的ptr查询请求分流给本地dhcp服务器。

**Comment by IrineSistiana** [comment]
做不到。这个名字不是 mosdns 说了算。
