### ISSUE TITLE
[Feature request] need a command line function to check syntax of config.yaml

### ISSUE THREAD

**Issue by fokker1027** [IrineSistiana/mosdns#20]
We need a function  to  check the syntax of config.yaml  without actual run.

建议命令行参数增加“-check” 或者“-test”来配合“-c“参数用以检查配置文件yaml的语法和有效性

**Comment by IrineSistiana** [comment]
非常实用的建议。

检查 yaml 格式靠大多数文本编辑器会更好些，让 mosdns 检查作用不大。

主要问题是配置文件有效性，但现在 mosdns 的加载方式很难检查插件内引用的 tag 是否正确。
