### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by thinker007** [IrineSistiana/mosdns#204]
是不是有内存泄露的问题，在AX86u上面运行一周时间内存占用高达700M

**Comment by IrineSistiana** [comment]
700M 很不正常。看起来是漏了。

配置文件？

top 或 htop 的截图？

**Comment by thinker007** [comment]
![Snipaste_2021-11-15_15-59-17](https://user-images.githubusercontent.com/1329869/141743806-860034bb-5d12-4471-adb0-84c8886244fd.png)

截图如上，配置文件一定需要么？

路由器 AX86u 梅林 3.2 操作系统

**Comment by IrineSistiana** [comment]
> 配置文件一定需要么

不一定全部。你告诉我你载入了多少域名和ip就行

**Comment by IrineSistiana** [comment]
RES 149M 算正常，如果你载入了很多很多域名的话。不要看 VIRT，那是虚拟内存不是实际占用。

你确定 RES 会随着使用时间变大么？

**Comment by thinker007** [comment]
res 149M 。。。。 这要是一个普通路由器 跑不了你这个啊。 目前查到原因了 ，用了增强版的geosite.dat 和 geoip.dat 导致内存占用较多。

**Comment by IrineSistiana** [comment]
我也用的增强版 dat。但也没那么多域名啊。我记得 geosite.dat 总共也就 20w 左右域名。

RES 149M 的话，估计你导入了将近 100w 域名？

我正常用加分流加广告过滤载入 15w 域名  RES 不过 30M。

**Comment by thinker007** [comment]
应该没有100w，就是用了增强版dat 文件，是不是里面某些正则表达式 导致内存爆了。

Irine Sistiana ***@***.***>于2021年11月16日 周二下午12:13写道：

> 我也用的增强版 dat。但也没那么多域名啊。
>
> RES 149M 的话，估计你导入了将近 100w 域名？
>
> 我正常用加分流加广告过滤载入 15w 域名 RES 不过 30M。
>

**Comment by IrineSistiana** [comment]
完整的配置文件能给我么。我本地跑一跑分析一下内存。

**Comment by thinker007** [comment]
> 完整的配置文件能给我么。我本地跑一跑分析一下内存。

[config.zip](https://github.com/IrineSistiana/mosdns/files/7567434/config.zip)

**Comment by thinker007** [comment]
这是配置文件，麻烦你啦~

**Comment by IrineSistiana** [comment]
你的配置文件我这里 RES 30M 很正常。你确定这个配置文件在路由器上 RES 149M?

**Comment by thinker007** [comment]
是的，我的路由器有1G内存，是不是跟这个有关系。

**Comment by IrineSistiana** [comment]
这就不清楚了。如果你确定是因为载入的域名多了，所以 RES 变大了，那可能就是和平台有关了。

既然不是内存泄漏。就关了。

**Comment by ShadowEmbrace** [comment]
> 

你好，我用的华硕AC66U_B1，原版梅林，想试着跑一下mosdns，用mosdns-linux-arm-7参照wiki的openwrt安装就可以么？谢谢！
