### ISSUE TITLE
[BUG]无法ping cdh相关的域名

### ISSUE THREAD

**Issue by ilanni2460** [IrineSistiana/mosdns#209]
hi，老铁，我这边使用mosdns提供的dns功能，无法ping通cdh的域名。mosdns的配置内容如下：
`log:
  level: debug
  file: /usr/local/mosdns/mosdns.log

plugin:

  - tag: inbound_server
    type: server
    args:
      entry:
        - default_cache             #先在缓存中查找，域名解析的IP地址
        - main_sequence
      max_concurrent_queries: 0  # 插件最大并发处理请求数。默认 0 代表无限制。
      server:
        - protocol: udp
          addr: :53
          timeout: 5
          idle_timeout: 10
        - protocol: tcp
          addr: :53
          timeout: 5
          idle_timeout: 10

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if_and:
            - query_local_hosts_prod_1         # 如果客户端请求指定的域名-生产内网解析
            - query_has_local_ip_prod
          exec:
            - forward_customize_dns_prod      # 使用生产自定义dns服务器
            - _end                            # 就直接采用结果

        - forward_public_dns             # 否则，最终使用公共dns服务器

  - tag: default_cache
    type: cache
    args:
      size: 1024000            # 缓存大小。单位: 条。默认: 1024。1w 条缓存大约会占用 1M 内存。
      lazy_cache_ttl: 0
      lazy_cache_reply_ttl: 30

  - tag: query_has_local_ip_prod
    type: query_matcher
    args:
      client_ip:
        - '58.59.130.0/24'

  - tag: query_local_hosts_prod_1
    type: query_matcher
    args:
      domain:
        - cdhserver1
        - cdhserver2

  - tag: forward_customize_dns_prod
    type: hosts
    args:
      hosts:
        - cdhserver1                                   58.59.18.60
        - cdhserver2                                   58.59.18.61

  - tag: forward_public_dns
    type: fast_forward
    args:
      upstream:
        - addr: 114.114.114.114
          trusted: true
          idle_timeout: 5
        - addr: 119.29.29.29
          trusted: true
          idle_timeout: 5`

在其他客户端ping cdhserver1，没有任何反应，而且mosdns上也没有该请求的任何日志。

老铁，帮忙看下是什么情况。

不知道是不是我的使用姿势对不对？

**Comment by ilanni2460** [comment]
具体配置文件，如下：
[prod_mosdns.zip](https://github.com/IrineSistiana/mosdns/files/7593753/prod_mosdns.zip)

**Comment by IrineSistiana** [comment]
不知道。

> 在其他客户端ping cdhserver1，没有任何反应，而且mosdns上也没有该请求的任何日志。

如果真的如你所说没有任何debug日志。那就是 mosdns 压根没受到请求。

**Comment by ilanni2460** [comment]
@IrineSistiana 你说的有可能，请求还没有到mosdns。
我抽空再测试下

**Comment by ilanni2460** [comment]
该issue关闭吧，在其他机器上测试是ok的
