### ISSUE TITLE
[BUG] 在arm、mips架构下编译报错！！！能否修复？！

### ISSUE THREAD

**Issue by zxlhhyccc** [IrineSistiana/mosdns#226]
经查，开启了cgo后上述架构下编译失败，关闭cgo后正常编译成功！但二进制比开启cgo编译出来的小！！！
![image](https://user-images.githubusercontent.com/45259624/147630115-9a223062-d4d2-4d75-8d61-a7b79652b47b.png)
![image](https://user-images.githubusercontent.com/45259624/147631067-2ada8d9c-394d-4a66-8931-6f563c4d6147.png)

**Comment by IrineSistiana** [comment]
为什么要开 cgo？

mosdns 并不需要 cgo。
