### ISSUE TITLE
[BUG]DoT 链接复用测试反馈EOF

### ISSUE THREAD

**Issue by QiuSimons** [IrineSistiana/mosdns#233]
![68B86059-8772-473E-9E46-B1BA9806B6C5](https://user-images.githubusercontent.com/45143996/147880518-4630ecc4-aabe-4a39-aa77-b1ebb3fed8db.jpeg)
如图，不确定和配置是否有关，有需要的话后补

**Comment by IrineSistiana** [comment]
dot的端口是853🌚

**Comment by QiuSimons** [comment]
我脑残了 当doh了
