### ISSUE TITLE
[Feature request]blackhole的IP地址能否支持从文件读取？

### ISSUE THREAD

**Issue by aa51513** [IrineSistiana/mosdns#236]
**希望添加的功能**
blackhole的结果IP(A记录和AAAA记录)从不同文件中读取

使用cloudflare优选IP，优选的IP经常更新，目前每次都要改mosdns的配置文件，然后重启，才能生效

能否考虑支持从文件中读取IP然后构造结果，这样就不用每次都去重启mosdns了

**Comment by IrineSistiana** [comment]
配置文件用 ${{}} 语法。

**Comment by aa51513** [comment]
> 配置文件用 ${{}} 语法。

这个${{cmd}}只有启动的时候，才会执行，不会热更新。
我想表达的是，热更新，就是改了文件，解析结果随之变化。

**Comment by IrineSistiana** [comment]
不考虑。太复杂。

**Comment by aa51513** [comment]
> 不考虑。太复杂。

了解了，感谢回复(❁´ω`❁)
