### ISSUE TITLE
mosdns V3.0发布了，docker镜像能帮忙更新一下吗？

### ISSUE THREAD

**Issue by aa51513** [IrineSistiana/mosdns#238]
不要在 issue 里提问。有问题请进入 Discussions 讨论。

[docker仓库](https://hub.docker.com/r/irinesistiana/mosdns/tags)最新版还是v2.2.2
希望能够及早更新一下

原因：文档已经更新，我用_return去配置，结果一直报错，看了好半天，才明白是docker镜像版本不是v3.0，不支持_return

**Comment by IrineSistiana** [comment]
docker 考虑到稳定性需要一般延后两三天更新
