### ISSUE TITLE
[Feature request]  forward里面的fastest_ip功能非常好用，能不能后台自动测速？

### ISSUE THREAD

**Issue by aa51513** [IrineSistiana/mosdns#239]
**希望添加的功能**

fastest_ip功能非常好用，会返回最快的IP地址
但只有每次请求DNS的时候，才会去测速，导致dns时间非常长，不利于用户体验

能不能在首次请求某个域名之后，后台自动测速（可以配置间隔、总运行时长），
这样下次再用的时候，直接就返回最快的IP地址

理由：用户经常访问的域名，实际上就那么几个，不会很多

**Comment by IrineSistiana** [comment]
不能。这是调用的 adguard home 的功能，我改不了。
