### ISSUE TITLE
_no_ecs配置后，好像没生效

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#251]
dig解析是带了ecs，每次解析都不能使用缓存，于是为了能够使用缓存，加了_no_ecs参数，但发现每次解析还是用不到缓存，请大佬指教

系统：amd64，版本：v3.0.0-0-gb2e0686
测试命令：dig youtube.com

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> youtube.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12307
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; PAD: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ("........................................................................................................................................................................................................................................................................................................................................................................................................................")
;; QUESTION SECTION:
;youtube.com.			IN	A

;; ANSWER SECTION:
youtube.com.		0	IN	A	172.217.14.110

;; Query time: 170 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jan 11 09:47:40 CST 2022
;; MSG SIZE  rcvd: 479

配置如下：
log:
  level: warn
  file: '/tmp/mosdns.log'

plugin:
  - tag: server
    type: server
    args:
      entry:
        - _no_ecs
        - hosts 
        - mem_cache
        - modify_ttl
        - main_sequence
      server:
        - protocol: udp
          addr: 127.0.0.1:53
        - protocol: udp
          addr: 192.168.21.1:53
        - protocol: tcp
          addr: 127.0.0.1:53
        - protocol: tcp
          addr: 192.168.21.1:53

  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 10240
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 2

  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - gfwlist
          exec:
            - _prefer_ipv4
            - forward_google
            - ipset 
            - _return

        - if:
            - '!gfwlist'
          exec:
            - _prefer_ipv4
            - forward_cn
            - _return

  - tag: forward_cn
    type: fast_forward
    args:
      upstream:
        - addr: https://doh.pub/dns-query
        - addr: https://223.5.5.5/dns-query
          idle_timeout: 10

  - tag: forward_google
    type: fast_forward
    args:
      upstream:
        - addr: tls://8.8.8.8
        - addr: tls://1.1.1.1
          idle_timeout: 8

  - tag: 'ipset'
    type: 'ipset'
    args:
      set_name4: 'gfwlist'
      set_name6: ''
      mask4: 0
      mask6: 0

  - tag: gfwlist
    type: query_matcher
    args:
      domain:
        - 'ext:./gfwlist.conf'
        - 'ext:./mylist.conf'

  - tag: 'hosts'
    type: 'hosts'
    args:
      hosts:
        - 'ext:./hosts'

**Comment by IrineSistiana** [comment]
dig 默认会带很多其他数据

用 dig +noedns youtube.com

**Comment by PHCSJC** [comment]
@IrineSistiana 
大佬你好，dig加了+noedns参数就会使用缓存，这个确实是这样，那mosdns里的_no_ecs不也是这个作用吗？为什么我在mosdns里加了这个参数后，用dig命令（不加+noedns）还是不会使用缓存呢？

换种方式说就是_no_ecs这个参数我好像试不出作用，是我哪里配置不对吗？我后来重测的时候把这个参数放在了执行序列最前面也不行。

另外smartdns是可以用到缓存的，不管dig加不加+noedns都能用到缓存

我主要担心浏览器会不会也发送带edns的选项，导致部分域名根本用不到缓存？所以就想测出dig不加+noedns也可以用到缓存的方法

**Comment by IrineSistiana** [comment]
> 我主要担心浏览器会不会也发送带edns的选项，导致部分域名根本用不到缓存？

edns = dns 扩展协议。服务器上常用。但正常的客户端都不会带这玩意，因为兼容性。

 ecs = edns client subnet.

edns != ecs. ecs 只是 edns  其一部分。

至于其他问题涉及到很多专业知识一两句话说不清。反正不用担心没换存。一定缓存了。

**Comment by IrineSistiana** [comment]
dig 会带很多 edns 项，去掉 ecs 不会去掉所有 edns。rfc 标准里 edns 项是禁止被缓存的。

**Comment by PHCSJC** [comment]
@IrineSistiana 感谢，我明白了，再请教下，就是怎么配置mosdns可以让dig不加+noedns也可以用到缓存，救救强迫症的孩子

**Comment by IrineSistiana** [comment]
没有办法。

dig edns 还带一个随机的 cookie，它这是故意不让服务器缓存，除非服务器不遵守规定。

**Comment by PHCSJC** [comment]
我之前用的smartdns，dig不加+noedns也可以用到缓存，这是为啥呢？他不遵守规定？

**Comment by IrineSistiana** [comment]
也不能说没遵守规定。它应该是压根就没管 edns 项。能用。但谁知道会不会出现不兼容的玄学 bug。

**Comment by PHCSJC** [comment]
明白了，非常感谢

**Comment by PHCSJC** [comment]
另外，发现一点，win上的nslookup和linux上的dig要共用缓存的话，dig命令需要加上这2个参数+noedns +noadflag
