### ISSUE TITLE
[Feature request]能否添加删除返回结果中的cname域名

### ISSUE THREAD

**Issue by w22gb8** [IrineSistiana/mosdns#256]
如果域名包含cname分流的时候要分别添加指定域名和canme域名，这不利于使用和维护。
示例：查询v.qq.com正常结果
v.qq.com.               52      IN      CNAME   v.tc.qq.com.
v.tc.qq.com.            160     IN      CNAME   v.qq.com.tdnsv6.com.
v.qq.com.sched.ssdv6.tdnsv6.com. 30 IN  A       1.1.1.1
v.qq.com.sched.ssdv6.tdnsv6.com. 30 IN  A       1.1.1.1

删除其中的cname域名返回，这样域名分流的时候只需添加v.qq.com，无需再添加v.tc.qq.com和v.qq.com.tdnsv6.com
v.qq.com.  30 IN  A       1.1.1.1
v.qq.com.  30 IN  A       1.1.1.1

**Comment by IrineSistiana** [comment]
> 如果域名包含cname分流的时候要分别添加指定域名和canme域名，这不利于使用和维护。

并不需要都指定。域名匹配的是question 的qname域名。不是 answer 的qname。所以只需匹配v.qq.com就行。

另，mosdns只是个转发器。像cname压缩这种功能暂不考虑实现。

**Comment by w22gb8** [comment]
> 

好像你没理解我的意思，如果分流只添加v.qq.com，当客户端只查询v.qq.com的cname v.tc.qq.com的a记录的时候不能分流了吧。

**Comment by IrineSistiana** [comment]
> 当客户端只查询v.qq.com的cname v.tc.qq.com的a记录的时候不能分流了吧。

客户端不查 cname。

**Comment by w22gb8** [comment]
我用unbound做前端会递归查询cname，参考mosdns代码写了个删除cname的插件，需要的可使用。
https://github.com/w22gb8/mosdns/commit/ed3ede2fd3b4a7b064b9eca42fecb2d9b3aa797d

**Comment by lengfwong** [comment]
> 如果域名包含cname分流的时候要分别添加指定域名和canme域名，这不利于使用和维护。 示例：查询v.qq.com正常结果 v.qq.com. 52 IN CNAME v.tc.qq.com. v.tc.qq.com. 160 IN CNAME v.qq.com.tdnsv6.com. v.qq.com.sched.ssdv6.tdnsv6.com. 30 IN A 1.1.1.1 v.qq.com.sched.ssdv6.tdnsv6.com. 30 IN A 1.1.1.1
> 
> 删除其中的cname域名返回，这样域名分流的时候只需添加v.qq.com，无需再添加v.tc.qq.com和v.qq.com.tdnsv6.com v.qq.com. 30 IN A 1.1.1.1 v.qq.com. 30 IN A 1.1.1.1



> > 当客户端只查询v.qq.com的cname v.tc.qq.com的a记录的时候不能分流了吧。
> 
> 客户端不查 cname。

Linux确实会有这样的现象：
Linux 系统中常用的 DNS 解析器（如 glibc 的 getaddrinfo 或 systemd-resolved）在查询域名时，通常会按以下步骤进行：
第一次查询 A 记录（IPv4 地址）。
如果返回包含CNAME 记录（别名记录），解析器会提取 CNAME 指向的目标域名。
第二次查询 AAAA 记录（IPv6 地址）时，使用的是 CNAME 指向的目标域名，而不是原始输入的域名。
这种行为是 Linux DNS 解析器设计的标准行为，遵循 RFC 1034 和 RFC 1035 的 DNS 规范。这种行为的根本原因在于 Linux 系统通常会更积极地遵循 DNS 协议中的CNAME（Canonical Name）记录,解析器会将后续查询基于 CNAME 的目标域名继续进行，以确保查询的是实际的资源记录。

windows 两次查询都只使用原始域名。

**Comment by lengfwong** [comment]
> 我用unbound做前端会递归查询cname，参考mosdns代码写了个删除cname的插件，需要的可使用。 [w22gb8@ed3ede2](https://github.com/w22gb8/mosdns/commit/ed3ede2fd3b4a7b064b9eca42fecb2d9b3aa797d)

大神，Linux确实会有这样的现象，Linux（glibc）第一次查询A记录，第二次查询AAAA记录。确实会在 A 查询发现 CNAME 后，把 CNAME 用作 AAAA 查询的目标域名。windows 两次查询都只使用原始域名。这个插件有更新吗？现在的5.3.3版本能用吗，直接exec dcname ？

**Comment by w22gb8** [comment]
> > 我用unbound做前端会递归查询cname，参考mosdns代码写了个删除cname的插件，需要的可使用。 [w22gb8@ed3ede2](https://github.com/w22gb8/mosdns/commit/ed3ede2fd3b4a7b064b9eca42fecb2d9b3aa797d)
> 
> 大神，Linux确实会有这样的现象，Linux（glibc）第一次查询A记录，第二次查询AAAA记录。确实会在 A 查询发现 CNAME 后，把 CNAME 用作 AAAA 查询的目标域名。windows 两次查询都只使用原始域名。这个插件有更新吗？现在的5.3.3版本能用吗，直接exec dcname ？

我在使用版本4，这个只适用于版本3，版本4官方有添加_misc_optm支持此功能，但是版本5貌似去除了这个功能。

**Comment by lengfwong** [comment]
> > > 我用unbound做前端会递归查询cname，参考mosdns代码写了个删除cname的插件，需要的可使用。 [w22gb8@ed3ede2](https://github.com/w22gb8/mosdns/commit/ed3ede2fd3b4a7b064b9eca42fecb2d9b3aa797d)
> > 
> > 
> > 大神，Linux确实会有这样的现象，Linux（glibc）第一次查询A记录，第二次查询AAAA记录。确实会在 A 查询发现 CNAME 后，把 CNAME 用作 AAAA 查询的目标域名。windows 两次查询都只使用原始域名。这个插件有更新吗？现在的5.3.3版本能用吗，直接exec dcname ？
> 
> 我在使用版本4，这个只适用于版本3，版本4官方有添加_misc_optm支持此功能，但是版本5貌似去除了这个功能。

有没有计划针对5版本重写这个插件？官方半年了没更新了。

**Comment by w22gb8** [comment]
> > > > 我用unbound做前端会递归查询cname，参考mosdns代码写了个删除cname的插件，需要的可使用。 [w22gb8@ed3ede2](https://github.com/w22gb8/mosdns/commit/ed3ede2fd3b4a7b064b9eca42fecb2d9b3aa797d)
> > > 
> > > 
> > > 大神，Linux确实会有这样的现象，Linux（glibc）第一次查询A记录，第二次查询AAAA记录。确实会在 A 查询发现 CNAME 后，把 CNAME 用作 AAAA 查询的目标域名。windows 两次查询都只使用原始域名。这个插件有更新吗？现在的5.3.3版本能用吗，直接exec dcname ？
> > 
> > 
> > 我在使用版本4，这个只适用于版本3，版本4官方有添加_misc_optm支持此功能，但是版本5貌似去除了这个功能。
> 
> 有没有计划针对5版本重写这个插件？官方半年了没更新了。

懒得折腾了 我用v4蛮稳的

**Comment by lengfwong** [comment]
> > > > > 我用unbound做前端会递归查询cname，参考mosdns代码写了个删除cname的插件，需要的可使用。 [w22gb8@ed3ede2](https://github.com/w22gb8/mosdns/commit/ed3ede2fd3b4a7b064b9eca42fecb2d9b3aa797d)
> > > > 
> > > > 
> > > > 大神，Linux确实会有这样的现象，Linux（glibc）第一次查询A记录，第二次查询AAAA记录。确实会在 A 查询发现 CNAME 后，把 CNAME 用作 AAAA 查询的目标域名。windows 两次查询都只使用原始域名。这个插件有更新吗？现在的5.3.3版本能用吗，直接exec dcname ？
> > > 
> > > 
> > > 我在使用版本4，这个只适用于版本3，版本4官方有添加_misc_optm支持此功能，但是版本5貌似去除了这个功能。
> > 
> > 
> > 有没有计划针对5版本重写这个插件？官方半年了没更新了。
> 
> 懒得折腾了 我用v4蛮稳的

参考原项目内容，让chatgpt写了V5版本的一个插件修改了下，测试通过了，请多指教。https://github.com/IrineSistiana/mosdns/issues/895
