### ISSUE TITLE
[Feature request] 远程动态数据更新

### ISSUE THREAD

**Issue by IrineSistiana** [IrineSistiana/mosdns#264]
计划中，不一定会实现:

- grpc 接口或订阅。
- 能远程更新 IP 和 域名表。
- 尽量不破坏现有的配置文件。

**Comment by mengxinz** [comment]
> 計劃中：
> 
> * grpc 介面。
> * 遠端更新IP和功能變數名稱表。
> * 盡量不破壞現有的配置檔。

下一次更新大约什么时候

**Comment by aa51513** [comment]
> 计划中:
> 
> * grpc 接口或订阅。
> * 能远程更新 IP 和 域名表。
> * 尽量不破坏现有的配置文件。

作者大大，我太爱你了

**Comment by hcwhan** [comment]
`远程更新 IP 和 域名表` 强烈需要 官方 docker 基于 alpine 没有 curl wget 等

**Comment by w22gb8** [comment]
可否添加远程更新要使用的forward服务器，配置文件内定义多个forward，然后远程可更改要使用的forward tag。

应用场景：多地区服务器动态选择最优的使用，同时使用其dns解析，目前使用nginx转发当中转，nginx动态更新upstream。

**Comment by aa51513** [comment]
这个特性，有进展吗？

**Comment by aa51513** [comment]
请问一下大佬，这个特性是正在进行中，还是放弃掉了？

**Comment by aa51513** [comment]
再来关注一下进展，期待作者能看到

**Comment by xiaolei0125** [comment]
@IrineSistiana  这个特性太赞了，如果可以支持远程动态更新ecs插件中的ipv4地址， 那么可以实现 : ecs插件支持动态设置或加载ipv4, 解决VPN内网下DNS的CDN问题 #447
