### ISSUE TITLE
[Feature request]可否添加查询log功能

### ISSUE THREAD

**Issue by w22gb8** [IrineSistiana/mosdns#268]
如：https://github.com/w22gb8/mosdns/commit/eaf87ab81b6821b18e8b8756187ebdcb06cf01ed#diff-c7166e9eb4552dd851099a28dd19663641558a06b092d8d9ba97a0a79f135039

**Comment by IrineSistiana** [comment]
使用场景是什么？

**Comment by w22gb8** [comment]
> 使用场景是什么？
就是单纯的记录下日志，方便分析查看。

**Comment by yuanhaoliang** [comment]
Rotate + gzip 挺有用的，如果打debug日志做分析的话。。。

**Comment by sjtuross** [comment]
查询日志对于调试也是有用的。在开启debug级别的日志时，是否能增加dns查询结果？

**Comment by urlesistiana** [comment]
新版本已实现。
