### ISSUE TITLE
[BUG] Openwrt 系统重启 interface 会导致 fast_forward 连接复用短时间无法连接到服务器

### ISSUE THREAD

**Issue by IrineSistiana** [IrineSistiana/mosdns#278]
目前发现 Openwrt 系统重启 interface (插拔网线，PPPoE 重登录等) 会导致启用了连接复用的 `fast_forward` 一段时间内无法连接到服务器，即使 interface 早已完成重启。

原因是 interface 重启后，这个 interface 相关的连接不会被 Openwrt 系统关闭。`fast_forward` 不知道已有的连接失效了，仍会继续使用旧连接直到 `idle_timeout` 超时。

目前没有解决方案，似乎 mosdns 做不了什么。只要 `idle_timeout` 不要设太长，就没什么影响。

**Comment by daiaji** [comment]
https://openwrt.org/docs/guide-user/base-system/hotplug
openwrt有HotPlug事件， /etc/hotplug.d目录下配脚本就完事了。
只是让钩子主动使mosdns重连很简单的。
`cat /etc/hotplug.d/iface/95-ddns `
```bash
#!/bin/sh

# there are other ACTIONs like ifupdate we don't need
case "$ACTION" in
        ifup)                                   # OpenWrt is giving a network not phys. Interface
                /etc/init.d/ddns enabled && /usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- start
                ;;
        ifdown)
                /usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- stop
                ;;
esac
```
但mosdns有命令参数能让mosdns重连吗？
这个事件应该是立马就会触发。
但这时候进行连接会有用吗？
可能ip都还没弄到。

**Comment by IrineSistiana** [comment]
是一个解决方案。没网没关系，只要 mosdns 不用旧连接就可以。

**Comment by daiaji** [comment]
openwrt自己的问题，就用openwrt自己的办法解决。
https://github.com/QiuSimons/openwrt-mos/blob/master/luci-app-mosdns/root/etc/hotplug.d/iface/99-mosdns
这边好像两个月前就弄了热插拔脚本。
不管用？

**Comment by IrineSistiana** [comment]
不清楚。我并不捣鼓路由。
