### ISSUE TITLE
redis连不上后，解析会报错，建议可以暂时屏蔽redis

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#284]
也不是所有解析会报错，发现这个程序会报错：
https://github.com/tickstep/aliyunpan/releases

试了下：把redis配置注释掉后正常了，或者把redis启动起来也会正常

为了避免单点故障，建议redis在连不上时可以暂时屏蔽掉redis

**Comment by IrineSistiana** [comment]
？

重新组织一下语言。完全没明白你是什么意思

**Comment by PHCSJC** [comment]
把redis服务关闭，mosdns解析会出错，但不是所有解析都会报错，我目前发现的主是的上面那个

**Comment by IrineSistiana** [comment]
你配置了 redis ，又把 redis 关掉，cache 当然报错。

没报错的是因没过 cache。

**Comment by PHCSJC** [comment]
是这意思，大佬，所以建议如果redis连不上了，解析也不会报错，就是跳过redis

**Comment by IrineSistiana** [comment]
redis 必需在线。至于用没用那是 cache 内部的细节。
