### ISSUE TITLE
[Feature request]能否考虑移植coredns里面的rewrite功能？

### ISSUE THREAD

**Issue by aa51513** [IrineSistiana/mosdns#285]
**希望添加的功能**
新增插件，移植coredns里面的rewrite功能

主要功能：重写dns请求中的域名，正常发送请求，然后重写dns响应中的域名，然后返回重写后的结果

在不修改域名的情况下，将请求导向另一个服务器，用于调试代码、排查问题

**Comment by IrineSistiana** [comment]
no。不造轮子。我也用的 coredns rewrite 套娃。
