### ISSUE TITLE
[BUG]fast_forward不处理truncated？

### ISSUE THREAD

**Issue by w22gb8** [IrineSistiana/mosdns#288]
新版本当消息超过512时fast_forward返回的截断的结果，forward会重新tcp返回完整的结果。

fast_forward当有tcp后端时也返回udp截断的结果。

**Comment by IrineSistiana** [comment]
没有tcp回滚。故意的。如果要转发 edns0 最好还是放弃udp协议。

**Comment by w22gb8** [comment]
> 没有tcp回滚。故意的。如果要转发 edns0 最好还是放弃udp协议。

哦，可否使用当udp返回truncated时如果有tcp后端就等待tcp返回的结果。

**Comment by IrineSistiana** [comment]
> > 没有tcp回滚。故意的。如果要转发 edns0 最好还是放弃udp协议。
> 
> 哦，可否使用当udp返回truncated时如果有tcp后端就等待tcp返回的结果。

之前想过这个方案，但是想了想最后还是放弃了。

dns over udp 毕竟是老古董规范了，为了兼容要用各种手段去处理报文 >512kybes 的情况。什么truncated，edns0 udp max size..... 很烦，也很不可靠。规范写的含糊，服务器实现也不一样。既然 mosdns 所有 dns 协议都支持，服务器现在也100%都有 tcp。为什么还要死守udp。

fastforward 的 tcp 还支持 rfc 7766 连接复用，用起来延时和 udp 一样，还能享受 tcp 的丢包快速重传，丢包不需要客户端重试响应时间大幅降低。

所以是故意放弃的。

**Comment by w22gb8** [comment]
明白了。
