### ISSUE TITLE
偶发性的cpu占用率高

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#293]
目前还没发现规律，就是有时会cpu占用率高，同样环境下smartdns不会超过5%。
![QQ截图20220215102326](https://user-images.githubusercontent.com/22064544/153981750-a1cae7ee-440b-4d63-b8d9-21b74bba8120.jpg)

配置如下：
plugin:
  - tag: server
    type: server
    args:
      entry:
        - hosts 
        - mem_cache
        - main_sequence
      server:
        - protocol: udp
          addr: 127.0.0.1:53
        - protocol: udp
          addr: 192.168.21.1:53
        - protocol: tcp
          addr: 127.0.0.1:53
        - protocol: tcp
          addr: 192.168.21.1:53

  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 65536
      redis: 'redis://localhost:6379/0'
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 1

  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  - tag: main_sequence
    type: sequence
    args:
      exec:

        - if:
            - gfwlist
          exec:
            - forward_google
            - ipset 
            - modify_ttl
            - _prefer_ipv4
            - _return

        - if:
            - '!gfwlist'
          exec:
            - forward_cn
            - modify_ttl
            - _prefer_ipv4
            - _return

  - tag: forward_cn
    type: fast_forward
    args:
      upstream:
        - addr: tls://dns.pub
        - addr: tls://223.5.5.5

  - tag: forward_google
    type: fast_forward
    args:
      upstream:
        - addr: tcp://8.8.8.8
        - addr: tcp://1.1.1.1

  - tag: 'ipset'
    type: 'ipset'
    args:
      set_name4: 'gfwlist'
      set_name6: ''
      mask4: 0
      mask6: 0

  - tag: gfwlist
    type: query_matcher
    args:
      domain:
        - 'ext:./gfwlist.conf'
        - 'ext:./mylist.conf'

  - tag: 'hosts'
    type: 'hosts'
    args:
      hosts:
        - 'ext:./hosts'

**Comment by IrineSistiana** [comment]
请按 bug 模板反馈问题。

**Comment by PHCSJC** [comment]
系统：arm64
版本：3.2
日志：没有报错
配置：
plugin:
  - tag: server
    type: server
    args:
      entry:
        - hosts 
        - mem_cache
        - main_sequence
      server:
        - protocol: udp
          addr: 127.0.0.1:53
        - protocol: udp
          addr: 192.168.21.1:53
        - protocol: tcp
          addr: 127.0.0.1:53
        - protocol: tcp
          addr: 192.168.21.1:53

  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 65536
      redis: 'redis://localhost:6379/0'
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 1

  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  - tag: main_sequence
    type: sequence
    args:
      exec:

        - if:
            - gfwlist
          exec:
            - forward_google
            - ipset 
            - modify_ttl
            - _prefer_ipv4
            - _return

        - if:
            - '!gfwlist'
          exec:
            - forward_cn
            - modify_ttl
            - _prefer_ipv4
            - _return


  - tag: forward_cn
    type: fast_forward
    args:
      upstream:
        - addr: tls://dns.pub
        - addr: tls://223.5.5.5

  - tag: forward_google
    type: fast_forward
    args:
      upstream:
        - addr: tcp://8.8.8.8
        - addr: tcp://1.1.1.1

  - tag: 'ipset'
    type: 'ipset'
    args:
      set_name4: 'gfwlist'
      set_name6: ''
      mask4: 0
      mask6: 0

  - tag: gfwlist
    type: query_matcher
    args:
      domain:
        - 'ext:./gfwlist.conf'
        - 'ext:./mylist.conf'

  - tag: 'hosts'
    type: 'hosts'
    args:
      hosts:
        - 'ext:./hosts'

**Comment by IrineSistiana** [comment]
只是瞬间高？

估计是新建 TLS 连接正在验证服务器证书吧。go 这块性能很不行。但下个月有大优化。

你可以禁用 tls 验证看看。
