### ISSUE TITLE
[Feature request] socks5支持

### ISSUE THREAD

**Issue by douglas-lee** [IrineSistiana/mosdns#3]
希望还是能支持socks5。

看到说明不支持socks5了，建议还是加上。因为在实际使用的场景中，需要走代理线路去解析dns以获得离代理服务器最优的解析结果。

**Comment by IrineSistiana** [comment]
程序请求上游的操作现在全交给 adhome 的 dnsproxy 了。dnsproxy 目前不支持 socks5，所以没办法。

什么时候 adhome 支持 socks5 了，mosdns 就能支持了。
