### ISSUE TITLE
[Feature request] 能否为hosts添加「域名 - 域名」映射

### ISSUE THREAD

**Issue by lflcan** [IrineSistiana/mosdns#301]
**希望添加的功能**

为 hosts 部分添加「域名 - 域名」映射的功能

mosdns 的 hosts 部分仅支持「域名 - IP」、「域名 - IP 数组」的映射，不支持「域名 - 域名」的映射
当前，v2ray 及 xray 均已实现 hosts 的「域名 - 域名」映射

「域名 - 域名」映射功能可为域名选择不同的 CDN 解析结果
比如将 Apple Music 在线播放域名 aod.itunes.apple.com 定向解析为以下 CDN 的 IP
网宿 hls.itunes.apple.com.mwcname.com 
阿里昆仑 aod.itunes.apple.com.w.alikunlun.com
金山云 aod.itunes.apple.com.download.ks-cdn.com
苹果自建 aod.itunes.g.aaplimg.com
而通过自选 CDN 能大幅改善 Apple Music 在线播放流畅度

**Comment by w22gb8** [comment]
arbitrary cname

**Comment by lflcan** [comment]
> arbitrary cname

能否给出一个 arbitrary cname 的示范，非常感谢！

**Comment by w22gb8** [comment]
> > arbitrary cname
> 
> 能否给出一个 arbitrary cname 的示范，非常感谢！

我试了下，貌似不行，客户端不递归查询返回的cname。

**Comment by w22gb8** [comment]
mosdns前加个unbound可解决：
```
  - tag: 'arbitrary'
    type: 'arbitrary'
    args:
      rr:
        - 'aod.itunes.apple.com IN A ANSWER aod.itunes.apple.com. IN CNAME hls.itunes.apple.com.mwcname.com'
```

**Comment by lflcan** [comment]
> mosdns前加个unbound可解决：
> 
> ```
>   - tag: 'arbitrary'
>     type: 'arbitrary'
>     args:
>       rr:
>         - 'aod.itunes.apple.com IN A ANSWER aod.itunes.apple.com. IN CNAME hls.itunes.apple.com.mwcname.com'
> ```

mosdns 前再添加 unbound 感觉不够简洁🤔，还是期待 mosdns 能在后续更新中加入 hosts 的「域名 - 域名」映射

**Comment by IrineSistiana** [comment]
如果要让客户端无感，要 rewrite 请求和应答。

不过我还是不理解

> **希望添加的功能**
> 
> 为 hosts 部分添加「域名 - 域名」映射的功能
> 
> mosdns 的 hosts 部分仅支持「域名 - IP」、「域名 - IP 数组」的映射，不支持「域名 - 域名」的映射 当前，v2ray 及 xray 均已实现 hosts 的「域名 - 域名」映射
> 
> 「域名 - 域名」映射功能可为域名选择不同的 CDN 解析结果 比如将 Apple Music 在线播放域名 aod.itunes.apple.com 定向解析为以下 CDN 的 IP 网宿 hls.itunes.apple.com.mwcname.com 阿里昆仑 aod.itunes.apple.com.w.alikunlun.com 金山云 aod.itunes.apple.com.download.ks-cdn.com 苹果自建 aod.itunes.g.aaplimg.com 而通过自选 CDN 能大幅改善 Apple Music 在线播放流畅度

为什么要自选 CDN？我测了一下 apple 的这个域名，已经是金山云 CDN 了，延时 10ms。

```
; <<>> DiG 9.17.8 <<>> aod.itunes.apple.com @223.5.5.5
;; QUESTION SECTION:
;aod.itunes.apple.com.          IN      A

;; ANSWER SECTION:
aod.itunes.apple.com.   1       IN      CNAME   aod.itunes.g.aaplimg.com.
aod.itunes.g.aaplimg.com. 1     IN      CNAME   aod-cn-lb.itunes-apple.com.akadns.net.
aod-cn-lb.itunes-apple.com.akadns.net. 1 IN CNAME aod.itunes.apple.com.download.ks-cdn.com.
aod.itunes.apple.com.download.ks-cdn.com. 1 IN CNAME k128.gslb.ksyuncdn.com.
k128.gslb.ksyuncdn.com. 1       IN      A       211.97.95.10
```

**Comment by lflcan** [comment]
> 如果要让客户端无感，要 rewrite 请求和应答。
> 
> 不过我还是不理解
> 
> > **希望添加的功能**
> > 为 hosts 部分添加「域名 - 域名」映射的功能
> > mosdns 的 hosts 部分仅支持「域名 - IP」、「域名 - IP 数组」的映射，不支持「域名 - 域名」的映射 当前，v2ray 及 xray 均已实现 hosts 的「域名 - 域名」映射
> > 「域名 - 域名」映射功能可为域名选择不同的 CDN 解析结果 比如将 Apple Music 在线播放域名 aod.itunes.apple.com 定向解析为以下 CDN 的 IP 网宿 hls.itunes.apple.com.mwcname.com 阿里昆仑 aod.itunes.apple.com.w.alikunlun.com 金山云 aod.itunes.apple.com.download.ks-cdn.com 苹果自建 aod.itunes.g.aaplimg.com 而通过自选 CDN 能大幅改善 Apple Music 在线播放流畅度
> 
> 为什么要自选 CDN？我测了一下 apple 的这个域名，已经是金山云 CDN 了，延时 10ms。
> 
> ```
> ; <<>> DiG 9.17.8 <<>> aod.itunes.apple.com @223.5.5.5
> ;; QUESTION SECTION:
> ;aod.itunes.apple.com.          IN      A
> 
> ;; ANSWER SECTION:
> aod.itunes.apple.com.   1       IN      CNAME   aod.itunes.g.aaplimg.com.
> aod.itunes.g.aaplimg.com. 1     IN      CNAME   aod-cn-lb.itunes-apple.com.akadns.net.
> aod-cn-lb.itunes-apple.com.akadns.net. 1 IN CNAME aod.itunes.apple.com.download.ks-cdn.com.
> aod.itunes.apple.com.download.ks-cdn.com. 1 IN CNAME k128.gslb.ksyuncdn.com.
> k128.gslb.ksyuncdn.com. 1       IN      A       211.97.95.10
> ```

V2ray 那边是 “若当前要查询的域名命中了 hosts 中的「域名 - 域名」映射，则该映射的值（另一个域名）将作为当前要查询的新域名，进入 DNS 处理流程，直到解析出 IP 后返回，或返回空解析”

Apple Music 我这边必须要自选 CDN，不自选的话就会飘到到网宿的节点上，返回一个延迟最低但实际体验最拉切歌卡到爆的 IP 上

**Comment by IrineSistiana** [comment]
了解了。

如果要 rewrite 请求和应答，挺麻烦的。coredns 有这功能，mosdns 不想再造个轮子。

不过如果想要换CDN，为什么不用hosts直接映射个IP，这个方法最简单。

~~v2ray 的 hosts 能提供一个参考连接么？我没找到相关的说明。想看看它是怎么处理 域名-域名 的。~~ 找到了。

**Comment by lflcan** [comment]
> 了解了。
> 
> 如果要 rewrite 请求和应答，挺麻烦的。coredns 有这功能，mosdns 不想再造个轮子。
> 
> 不过如果想要换CDN，为什么不用hosts直接映射个IP，这个方法最简单。
> 
> ~v2ray 的 hosts 能提供一个参考连接么？我没找到相关的说明。想看看它是怎么处理 域名-域名 的。~ 找到了。

感觉套娃使用多个 DNS 服务不够简洁，怕引起冲突

而据我这边的观察，这些 CDN 的 CNAME 域名会定时更新 IP，高峰时段还会进行负载均衡提供不同的 IP，如果只是 hosts 直接映射 IP 就要时不时地改配置文件，还是挺麻烦的

**Comment by liangxyz** [comment]
> 了解了。
> 
> 如果要 rewrite 请求和应答，挺麻烦的。coredns 有这功能，mosdns 不想再造个轮子。
> 
> 不过如果想要换CDN，为什么不用hosts直接映射个IP，这个方法最简单。
> 
> ~v2ray 的 hosts 能提供一个参考连接么？我没找到相关的说明。想看看它是怎么处理 域名-域名 的。~ 找到了。

请问作者，type: 'blackhole' 是否支持以 `ext:` 开头，从外部文件导入数据？

**Comment by IrineSistiana** [comment]
@liangxyz no

**Comment by aa51513** [comment]
> > 了解了。
> > 如果要 rewrite 请求和应答，挺麻烦的。coredns 有这功能，mosdns 不想再造个轮子。
> > 不过如果想要换CDN，为什么不用hosts直接映射个IP，这个方法最简单。
> > ~v2ray 的 hosts 能提供一个参考连接么？我没找到相关的说明。想看看它是怎么处理 域名-域名 的。~ 找到了。
> 
> 感觉套娃使用多个 DNS 服务不够简洁，怕引起冲突
> 
> 而据我这边的观察，这些 CDN 的 CNAME 域名会定时更新 IP，高峰时段还会进行负载均衡提供不同的 IP，如果只是 hosts 直接映射 IP 就要时不时地改配置文件，还是挺麻烦的

同样需要这样的功能😲😲😲😲😲

**Comment by IrineSistiana** [comment]
839c300a8e5245ea4aad896be4177c1c014b586e 

redirect 插件。重定向(改写)请求的域名。

```yaml
  - tag: redirect
    type: redirect
    args:
      rule:
     # - [域名规则] [重定向域名] 
        - baidu.com dns.google
        - ext:./file.txt
```


```txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35712
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              534     IN      A       8.8.4.4
baidu.com.              534     IN      A       8.8.8.8

;; Query time: 177 msec
;; SERVER: 127.0.0.1#5533(127.0.0.1) (UDP)
;; WHEN: Thu Mar 10 09:31:44 China Standard Time 2022
;; MSG SIZE  rcvd: 88
```

[域名规则] 和 hosts 一样。默认 full 匹配。支持其他匹配方式。可以从外部文件载入。

只是复制替换了请求的域名。请求 A/AAAA 记录应该没问题。不保证请求其他类型的记录能兼容。
