### ISSUE TITLE
[BUG]fast_forward 的timeout无效

### ISSUE THREAD

**Issue by lix5027** [IrineSistiana/mosdns#302]
测试时候发现,udp方式,随便给一个ping不通假ip地址(比如192.168.255.255)
fast_forward即使设置了1秒timeout,结果还是会等很久
ad的forward方式,设置1秒,到时候就会继续序列了

##########
  - tag: checkdns
    type: fast_forward
    args:
      upstream:
        - addr: '192.168.255.255'
      timeout: 1

##########
如图,fast模式的timeout1秒无效,普通forward可以正确到1秒结束

另外,可否将timeout改为毫秒?我试了下0.1秒,在forward下是无效的,如果修正fast的这个bug,可否将小数点引入,或者单位为毫秒,谢谢!

**Comment by lix5027** [comment]
我的网络环境可以测试域名污染

比如我udp53方式检索www.youtube.com 到 一个假ip上(ping不通,也没dns53)

如果是污染的域名,会在20ms内给我反馈投毒结果
如果没问题,则会超时

所以我想用fast_forward 方式
timeout=50ms
来实现投毒判断,

只要50ms以内给我反馈结果(用rcode0判断)的就走remote序列
否则就走local序列

**Comment by IrineSistiana** [comment]
Fast_forward 的 timeout  v3 版本后就无效了。

现在由 server 的 timeout 统一控制所有插件和操作的时间底线。

forward 调用的其他的包，不支持统一 timout 控制。

**Comment by lix5027** [comment]
> 

那像我这样想实现50毫秒反馈结果=投毒,>50毫秒则放行
就无法实现了?

**Comment by IrineSistiana** [comment]
> > 
> 
> 那像我这样想实现50毫秒反馈结果=投毒,>50毫秒则放行 就无法实现了?

曾经我也这么想过。而且我也这样干过。

结论是不靠谱。很容易网络波动一下。有个假应答的延时过了你设定的阈值。就缓存污染了。
