### ISSUE TITLE
[Feature request]redis服务器不可用时候进程会卡住

### ISSUE THREAD

**Issue by lix5027** [IrineSistiana/mosdns#303]
测试环境是4台dns使用同一个redis服务器做物理缓存
当redis服务器重启的时候,4台dns服务器会卡死
可否为redis做一个接口timeout或者判断

**Comment by yuanhaoliang** [comment]
当Redis连不上的时候，退化成用本地内存？如何？做个fallback机制。

**Comment by IrineSistiana** [comment]
我觉得吧。当使用者设定 redis 做后端的时候。就有责任保证 redis 在线。

让 mosdns 检测 redis 是否可用然后是否要绕过有点没必要。

上 redis 高可用吧。

**Comment by IrineSistiana** [comment]
unbound:

>  If  Unbound  was  built with --with-libhiredis on a system that has in-
>        stalled the hiredis C client library of Redis, then the "redis" backend
>        can be used.  This backend communicates with the specified Redis server
>        over a TCP connection to store and retrieve cache data.  It can be used
>        as  a  persistent and/or shared cache backend.  It should be noted that
>        Unbound never removes data stored in the Redis  server,  even  if  some
>        data  have  expired  in terms of DNS TTL or the Redis server has cached
>        too much data; if necessary the Redis  server  must  be  configured  to
>        limit  the cache size, preferably with some kind of least-recently-used
>        eviction policy.  Additionally, the redis-expire-records option can  be
>        used  in order to set the relative DNS TTL of the message as timeout to
>        the Redis records; keep in mind that some additional memory is used per
>        key  and  that  the expire information is stored as absolute Unix time-
>        stamps in Redis (computer time must be stable).  This backend uses syn-
>        chronous  communication  with  the Redis server based on the assumption
>        that the communication is stable and  sufficiently  fast.   The  thread
>        waiting  for  a  response from the Redis server cannot handle other DNS
>        queries.  Although the backend has the  ability  to  reconnect  to  the
>        server  when  the connection is closed unexpectedly and there is a con-
>        figurable timeout in case the server is overly slow or hangs up,  these
>        cases are assumed to be very rare.  If connection close or timeout hap-
>        pens too often, Unbound will be effectively unusable with this backend.
>        It's the administrator's responsibility to make the assumption hold.

fallback 真没必要。设定 redis 做后端的时候。就有责任保证 redis 在线。

设置 timeout，临时容错，比较实用。

**Comment by yuanhaoliang** [comment]
> 

有道理。

**Comment by lix5027** [comment]
我也认为设置timeout合适,超时后继续序列,先跑着

**Comment by IrineSistiana** [comment]
timeout 50ms。

如果有一次超时，则假设 redis server 有问题。

一秒内的所有请求都会绕过 redis。即使 redis server 离线，也不会导致所有请求都加了 50ms 延时。
