### ISSUE TITLE
[BUG] 今天才試了一下redis，但好像都被skipped

### ISSUE THREAD

**Issue by sammimk830** [IrineSistiana/mosdns#304]
**出现了什么问题**

简要描述一下问题的表现，以及执行了什么操作导致了问题的出现：

發現如果不把cache_everything改為true，就基本都不保存到redis了，直接skipped。感覺是不是这里有點問題？
![image](https://user-images.githubusercontent.com/34807325/155854225-a5cd709e-9238-471f-8024-7139cd5703de.png)

mosdns 的 log 记录:

```txt

```
![image](https://user-images.githubusercontent.com/34807325/155854106-201e650c-7161-4364-ab70-03366ab62e50.png)

---

**环境**

描述一下问题出现的环境，便于复现以更快定位问题。必须包含：

mosdns 的版本号(`mosdns -v`)：v3.3.0-0-g2287bd5

操作系统和平台：ubuntu 20.04

使用的配置文件：

```yaml

````

**Comment by IrineSistiana** [comment]
Cache 默认只缓存简单请求。wiki 里写的很清楚。
