### ISSUE TITLE
[Feature request]dns over quic搞个呗。

### ISSUE THREAD

**Issue by daiaji** [IrineSistiana/mosdns#307]
https://datatracker.ietf.org/doc/html/draft-huitema-quic-dnsoquic-07
好像有草案。
AdGuard Home有实现。
可以抄-w-

**Comment by IrineSistiana** [comment]
forward 有。

**Comment by daiaji** [comment]
服务端？

**Comment by IrineSistiana** [comment]
这个草案可能快凉了。

现在流行 dns over http。用 http3。也算 dns over quic

**Comment by daiaji** [comment]
本质上一个东西吧，只是http3现在还在扯皮，我不知道这个是基于谷歌弄出来的quic还是ietf在推进的qeic。不过后者也是ietf把谷歌的quic中的加密部分换成标准的tls弄出来的吧。

**Comment by daiaji** [comment]
不过谷歌原版的qeic基本上没人管了吧，用它造DNS感觉不太可能，dot有固定端口容易被直接ban，doq复用http3的端口，隐蔽性好点。基本上可以认为现在的qeic就是beta版的http3，正式标准推行的时候更新库的版本就行了，大差不差的。

**Comment by IrineSistiana** [comment]
和你说的那个草案本质上差一个 http。

quic 已经是 rfc9000 了。http3 这架势迟早 rfc。毕竟厂大有话讲。dns.google 之前也悄悄地支持 dns over http3 了。

**Comment by IrineSistiana** [comment]
有支持 quic 的想法，但不是那个草案。而是 http3。

**Comment by daiaji** [comment]
说到http3我就恼火，本身http2也是Google在推进，quic也是Google弄得，说是要起新标准，Google就直接把quic拿来用，这群铁憨憨拿现成的东西来定个标准，2015年就开始议，议到现在，Google公开测试这玩意2013年就开始搞了，到底效率要低到什么地步才能慢成这样。

**Comment by IrineSistiana** [comment]
~他家的quic库性能太拉~

**Comment by daiaji** [comment]
> ~他家的quic库性能太拉~

说不定90%时间是在扯皮呢？
就像html5那样~

**Comment by daiaji** [comment]
那么多家商业公司在弄一个项目，搞了7年，不是天天摸鱼，怎么着现在也弄出来了吧，就是个人开发者怼着原版quic搞优化，7年也收工了，到底要内耗到什么地步才能搞这么久？怕不是苹果和谷歌天天在干架才能慢成这样。

**Comment by IrineSistiana** [comment]
搞不动。

今天又试了试 go 的 quic 库，win 上反正我是没搞起来，切个网就再也连不上了。linux 还没试。看 AdGuard Home 那边的 issue 听说 mips 架构还会直接崩。暂时不会有支持 quic 的想法。

**Comment by daiaji** [comment]
https://github.com/systemd/systemd/issues/23770
咋回事？
咋dns over quic还在推进？

> DNS over HTTPS (DoH) [[RFC8484](https://datatracker.ietf.org/doc/html/rfc8484)] can be used with HTTP/3 to get some of
>    the benefits of QUIC.  However, a lightweight direct mapping for DoQ
>    can be regarded as a more natural fit for both the recursive to
>    authoritative and zone transfer scenarios, which rarely involve
>    intermediaries.  In these scenarios, the additional overhead of HTTP
>    is not offset by, for example, benefits of HTTP proxying and caching
>    behavior.

这是不是说dns over quic和dns over http/3是两个线路了？
https://datatracker.ietf.org/doc/html/rfc9114
叼，六月六号HTTP/3正式标准化了呀。

**Comment by daiaji** [comment]
@urlesistiana 现在dns over quic和dns over http/3的库能用了吗？

**Comment by cherinyy** [comment]
其实 DoQ 的标准化时间比 HTTP/3 还早完成。

[RFC 9114 - HTTP/3](https://datatracker.ietf.org/doc/html/rfc9114)：2022 年 6 月

[RFC 9250 - DNS over Dedicated QUIC Connections](https://datatracker.ietf.org/doc/html/rfc9250)：2022 年 5 月

AdGuard 团队关于[为何 DNS-over-QUIC 不是 DNS-over-HTTPS](https://adguard-dns.io/blog/dns-over-quic.html#dnsoverhttps) 的解释：

> 事实上有几种原因，但它们都源自于 **HTTP 不是传输层协议**的问题。HTTP 是为其他原因创造的。如果使用它作为传输层协议，这会引起[很多不必要的风险](https://tools.ietf.org/html/rfc8484#section-8.2)。特别是在私密区。使用 HTTP 以发送 DNS 请求会导致下列结果：
> 
> - HTTP cookies
> - 其他 HTTP 消息头（HTTP headers）（包括 Authentication, User-Agent, Accept-Language）
> - 给预谋犯更多机会
> - [用 ETag 来跟踪用户](https://zh.wikipedia.org/wiki/HTTP_ETag#%E7%94%A8ETag%E6%9D%A5%E8%B7%9F%E8%B8%AA%E7%94%A8%E6%88%B7)
> 
> 每一个问题可以在客户端的 DoH 级被解决，但是现在有各种不同的客户端：浏览器、操作系统，不少其他软件，但无法对每一个客户端都提供量身定做的解决方案。

然而至今没有大厂愿意跟进 DoQ，包括号称优先保障隐私的 [1.1.1.1](https://1.1.1.1/zh-Hans/dns/)。

**Comment by cherinyy** [comment]
目前[阿里DNS](https://www.alidns.com/)已支持 DoQ：

```
> dnslookup github.com quic://dns.alidns.com
dnslookup v1.9.2
dnslookup result (elapsed 79.5974ms):
;; opcode: QUERY, status: NOERROR, id: 3841
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags:; udp: 4096

;; QUESTION SECTION:
;github.com.    IN       A

;; ANSWER SECTION:
github.com.     15      IN      A       20.205.243.166
```

**Comment by cherinyy** [comment]
[5.2.1](https://github.com/IrineSistiana/mosdns/releases/tag/v5.2.1) 版本已支持 DoQ 🎉，感谢 Irine！

**Comment by daiaji** [comment]
> [5.2.1](https://github.com/IrineSistiana/mosdns/releases/tag/v5.2.1) 版本已支持 DoQ 🎉，感谢 Irine！

DoQ怎么部署？不需要CA签署的证书吧？

**Comment by cherinyy** [comment]
> DoQ怎么部署？不需要CA签署的证书吧？

肯定是需要数字证书的。

https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/fu-wu-qi-cha-jian#quic_server

**Comment by TMXQWQ** [comment]
草我从systemd那边来的,那边有个人提到了这个issues(
