### ISSUE TITLE
[BUG] 配置文件 ${{}} 自生成功能有安全问题

### ISSUE THREAD

**Issue by IrineSistiana** [IrineSistiana/mosdns#309]
最开始设计的时候没考虑太多。导致了几个严重问题。

1. 由于 `${{}}`  会执行其他代码。导致被报毒了。当然是误报。不过很烦。
2. 处理配置文件没有安全检查。如果配置文件有恶意的东西会出问题。

~目前计划 v4 版本去掉这个功能，或者增加限制。~

使用时请注意安全问题。

**Comment by ShinyNito** [comment]
把这个分离出来变成插件. 然后定期运行是否可以. 
目前需求是家里使用 需要根据代理IP来指定ECS IP.

**Comment by QiuSimons** [comment]
这个功能讲道理还是方便的，如果去掉的话，很多现在能轻易实现的功能不太好搞了.......

**Comment by IrineSistiana** [comment]
安全的做法是用脚本先按配置模板生成一个配置然后启动程序。

作为一个 DNS 转发器，能执行任意代码，过头了。

**Comment by IrineSistiana** [comment]
不改了。

巨硬的WD报毒就TM是玄学，不管了不管了。

**Comment by QiuSimons** [comment]
举杯庆祝...

**Comment by XuuKoo** [comment]
> 不改了。
> 
> 巨硬的WD报毒就TM是玄学，不管了不管了。

想问下 V4 版本里是不是不支持 这个功能了？

之情v3的时候利用批处理获取dhcp的ip地址，一切正常，迁移到v4的配置文件里就用不了了：
invalid server address, parse "udp://${{get_dhcp_ip.bat}}": invalid character "{" in host name
