### ISSUE TITLE
[Feature request]从嵌套的sequence中直接返回并结束流程

### ISSUE THREAD

**Issue by sjtuross** [IrineSistiana/mosdns#317]
为了避免主sequence过长，嵌入了一个子sequence，根据log判断在嵌套的sequence中使用_return会返回上层sequence继续执行。

实际情况是嵌套的sequence中已经得到了查询结果，为了避免主sequence继续执行还得另外添加排除条件，过于冗余，失去了分拆的意义。

记得之前有个_end，是否可定义为返回并终止执行？

**Comment by wy16W2pIilK1xgqN** [comment]
我也遇到了相同的问题，希望能改进一下。
对于 “_retum” 这个功能我觉的可以扩展一下，借鉴编程语言中常见的跳转 “Jump”

用户在配置中设定跳转点“anchor” ，然后用 jump 命令 跳转过去。
还可以区分 sequence内部的局部锚点和sequence全部有效的全局锚点 .

比如
设定局部锚点 
`anchor:"aaa"`
全局锚点
`_anchor:"bbb"`
跳转
`jump:"aaa"`

**Comment by urlesistiana** [comment]
v5 已实现。
