### ISSUE TITLE
[Feature request] query_matcher匹配器支持来源ipset

### ISSUE THREAD

**Issue by sjtuross** [IrineSistiana/mosdns#318]
预先定义了一个来源 ipset (比如：192.168.1.6 - 192.168.1.55 这个地址段以及另外几个ip) 走联通线路，然后希望通过mosdns让这批客户端用联通dns，利用这个现成的ipset来匹配客户端查询请求。如果用现有的client_ip，就得重新定义一遍

**Comment by w22gb8** [comment]
ipset的作用是可以动态更新规则吧，client_ip用tag也可以多次调用啊。

**Comment by sjtuross** [comment]
我希望实现的是避免重复定义，倒不是动态加载，但也是一个好处。预先定义的ipset还用在策略路由上，并不只是mosdns

**Comment by IrineSistiana** [comment]
ipset 即将成为历史。不再考虑继续加功能。
