### ISSUE TITLE
[BUG] 最新的openwrt开启mosdns后 登录界面进不去。

### ISSUE THREAD

**Issue by jiatianxa** [IrineSistiana/mosdns#319]
**出现了什么问题**

简要描述一下问题的表现，以及执行了什么操作导致了问题的出现：
最新的openwrt开启mosdns后，OpenClash开启， 输入路由ip登录界面进不去。
mosdns 的 log 记录:

```txt

```

---

**环境**

描述一下问题出现的环境，便于复现以更快定位问题。必须包含：

mosdns 的版本号(`mosdns -v`)：v3.1.2

操作系统和平台：openwrt 内核版本5.15.29

使用的配置文件：

默认原始配置档
```yaml

````
![无标题3](https://user-images.githubusercontent.com/12829666/159147644-1fc1863e-1950-44f3-b51c-3dfdb5e8fa14.png)
![无标题4](https://user-images.githubusercontent.com/12829666/159147646-be42bd64-b508-4be8-a4e2-476ec1d2d8e2.png)

**Comment by IrineSistiana** [comment]
反馈错地方了。
