### ISSUE TITLE
[BUG] 3.7版本日志有大量failed to add response IP to ipset

### ISSUE THREAD

**Issue by vrichv** [IrineSistiana/mosdns#330]
### Bug 描述和复现步骤(必填): 
从2.1升级3.7之后日志有大量warn提示，回退到3.6版本消失：
2022-04-05T15:52:24.381Z	warn	ipset_chinaip	ipset/ipset.go:72	failed to add response IP to ipset	{"query": "weibo.com. IN A 29530 10 192.168.137.4", "error": "failed to add ip 39.156.6.91 to set chnroute: protocol not available"}
2022-04-05T15:52:25.736Z	warn	ipset_chinaip	ipset/ipset.go:72	failed to add response IP to ipset	{"query": "i.sso.sina.com.cn. IN A 30922 14 192.168.137.4", "error": "failed to add ip 112.48.132.101 to set chnroute: protocol not available"}

### mosdns 的版本号(必填):
3.7

### 操作系统和 CPU 架构(必填):
linux mips

### 使用的配置文件(必填):
<details><br><pre>
log:
  level: info 
  file: ""

plugin:
  - tag: main_server    # 启动服务器
    type: server
    args:
      entry:
        - cache          # 缓存
        - _single_flight
        - main_sequence
      max_concurrent_queries: 0
      server:
        - protocol: udp
          addr: 0.0.0.0:53

  ################# 主执行流程定义 ################
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain    # 已知的广告域名
            - "!_query_is_common"     # 和不常见的请求类型
          exec:
            - _block_with_nxdomain  # 屏蔽
            - _return

        - if:
            - query_is_local_domain   # 已知的本地域名
          exec:
            - forward_local           # 用本地服务器
            - ipset_chinaip           #ipset whitelist
            - _return

        - forward_local_gz
          
  - tag: 'cache'
    type: 'cache'
    args:
      size: 4096  
      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 30 
  ################ DNS服务器配置 #################
  - tag: forward_local # 本地DNS解析
    type: fast_forward
    args:
      upstream:
        - addr: https://dns.alidns.com/dns-query                                                                                     
          dial_addr: '223.5.5.5:443' 
          idle_timeout: 30    
          max_conns: 5    

  - tag: forward_local_gz 
    type: forward
    args:
      upstream:
        - addr: quic://c.passcloud.xyz:784                                                                                       
          ip_addr: '42.194.141.208'  
          trusted: true

  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:cn"

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:geolocation-!cn" #geolocation-!cn #category-anticensorship

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:category-ads-all" #category-ads-all：1688 false

 - tag: ipset_chinaip    
    type: ipset
    args:                                           
      set_name4: "chnroute"
      mask4: 24
                                                  
include: [ ]

</pre></details>

### mosdns 的 log 记录:

<details><br><pre>

</pre></details>

**Comment by IrineSistiana** [comment]
看起来是 netlink 包大更新出问题了。已回退。

**Comment by vrichv** [comment]
@IrineSistiana  这个bug在 3.9版本又出现了。

**Comment by IrineSistiana** [comment]
试试 4495ae82a48de06790de157edbe038ba01116d3d
