### ISSUE TITLE
[BUG] modify_ttl不生效

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#334]
就是这个配置：本地/远程域名分流 + 广告屏蔽。点击展开

修改ttl不生效，最新的v3.7.2版本，如果放到 main_sequence后面，就会生效

**Comment by IrineSistiana** [comment]
正常。大多数域名都已经 return 了不会轮到 modify_ttl。

wiki 里的模板逻辑上是有点问题。会改，

**Comment by PHCSJC** [comment]
这个sequence有时确实不太好理解，mem_cache为什么会在广告之后呢，不应该是在序列最后再cache吗？
虽然我知道正确的配置就应该在那，只是随便叨叨

还有server是不是也是一个sequence，因为我发现modify_ttl要放在main_sequence后面，放在前面就不行了

所以有了上面的感慨，有点乱，有时只能靠试

**Comment by IrineSistiana** [comment]
没办法。插件的运行顺序其实不是依次而是“栈”。“栈”这玩意不好解释。。。。

**Comment by PHCSJC** [comment]
其实不用解释栈的，只要说明插件在哪些情况下应该放在哪个位置就可以了，希望大佬能在wiki再详细说明下，再请教大佬一个问题，就不新开issue了，自定义的hosts应该放在哪呢？

是放在这个位置吗？如果这个位置，在读取到hosts后获得解析后，还会继续执行后面的序列吗？如果还会执行，那是不是会有点影响解析速度了？
      entry:
        - hosts 
        - main_sequence
        - modify_ttl


或者放在这个后面吗？
 - tag: main_sequence
    type: sequence
    args:
      exec:
        - _prefer_ipv4

**Comment by IrineSistiana** [comment]
wiki 上写的很清楚吧/

> 如果域名在 hosts 内，则生成应答并跳过后续插件。如果不在，则继续执行后续插件。

**Comment by PHCSJC** [comment]
抱歉，确实有，我的问题
