### ISSUE TITLE
大佬，建议增加一项功能

### ISSUE THREAD

**Issue by Wanderingkang** [IrineSistiana/mosdns#336]
事情起因是这样的，我看到好多人都有这样的需求，大家都在使用fake-ip模式，但是国内的想用真实ip，所以我有个想法就是客户端请求的流量到mosdns，mosdns通过判断clash的规则文件，选择走fake还是真实ip！如果用geoip.dat:cn，有的域名出现不正常现象，感谢大佬

**Comment by IrineSistiana** [comment]
不行。不是不想，是原理上实现不了。

mosdns 是没有办法和 clash 的 fake ip 联动的。

**Comment by IrineSistiana** [comment]
> mosdns通过判断clash的规则文件

太麻烦。没计划。

但是 mosdns 可以配置成和 clash 一样的规则。如果规则一样则不应该出现有问题的域名。

**Comment by IrineSistiana** [comment]
> 不行。不是不想，是原理上实现不了。
> 
> mosdns 是没有办法和 clash 的 fake ip 联动的。

我想多了。可以联动。你只需要在mosdns里把非国内域名转发给 clash 的 dns 端口就行了。国内域名正常转发给上游服务器。

**Comment by Wanderingkang** [comment]
是不是可以这样，就是把clash的规则文件直接挂进来，我挂了规则的yaml文件，报错。主要是不想把域名文件来回转换

**Comment by Wanderingkang** [comment]
clash 的规则文件样式为：direct.yaml
payload:
  - '+.0-100.com'
  - '+.0-6.com'
  - '+.0-gold.net'
  - '+.00.net'
主要想挂载这个文件
