### ISSUE TITLE
[Feature request] cache 插件支持ECS IP 属性

### ISSUE THREAD

**Issue by Alion548** [IrineSistiana/mosdns#338]
当同时启用cache和ecs功能时，缓存结果同时记录ecs ip

如：
ecs ip: 1.1.1.0/24 请求www.domain.com，结果 4.4.4.4（正确）
ecs ip: 2.2.2.0/24 请求www.domain.com，结果 4.4.4.4（错误，正确结果：5.5.5.5）

**Comment by IrineSistiana** [comment]
没看懂。

**Comment by Alion548** [comment]
解决了，要先附加ecs ip，再缓存。作者这工具真牛逼

**Comment by zhmars** [comment]
> 解决了，要先附加ecs ip，再缓存

这里的解决是不是还应该开启 `cache_everything`？否则虽然可以得到正确结果，实际上并没有缓存，每次都是重新请求。

**Comment by Alion548** [comment]
> > 解决了，要先附加ecs ip，再缓存
> 
> 这里的解决是不是还应该开启 `cache_everything`？否则虽然可以得到正确结果，实际上并没有缓存，每次都是重新请求。

应该不用，我理解的cache_everything是指缓存不常用类型的查询，比如非A、AAAA记录

**Comment by zhmars** [comment]
缓存不常用类型的查询是一方面，这里开启它是为了缓存带 ECS 信息的 A/AAAA 请求。在我的实际测试里面，默认的缓存并不支持这样的请求。

**Comment by IrineSistiana** [comment]
ecs 属于 dns 扩展协议。默认不缓存。
