### ISSUE TITLE
[BUG] redis缓存达到8000后变非常慢

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#339]
debian10，mosdns-3.7.3，redis-5.5

配置文件就是：本地/远程域名分流 + 广告屏蔽

现象是，缓存为0时，速度都正常，但缓存达到较大的数，我这观察到的是8000个后，再重启mosdns，发现解析会非常慢（好像是fast_forward慢），然后把配置文件里的redis注释掉，马上就正常了。

硬件的配置：i5-7200u，4G内存

**Comment by IrineSistiana** [comment]
开 dubug 日志看看时间，能算出插件的耗时，就能看出哪插件出问题了。

redis 我也在用。几十万缓存没问题。

最好把 debug 日志贴过来。

**Comment by PHCSJC** [comment]
我又试了试，不是变慢，是ipset没有添加ip

我这的重现步骤（100%重现）：
ipset flush gfwlist
killall mosdns
nohup mosdns -dir /etc/mosdns -c /etc/mosdns/config.yaml >/dev/null 2>&1 &

电脑操作：
ipconfig /flushdns
nslookup www.google.com

此时再去软路由上查ipset
ipset list | grep '电脑上解析出的ip'
发现并没有这个ip，所以电脑上google打不开


继续另一个测试：
把redis注释掉，重启mosdns，继续上面完全一样的操作，此时发现ipset里是有google的ip的。

说明并不是电脑DNS配置问题，问题就是出在mosdns本身。

**Comment by IrineSistiana** [comment]
知道问题了。

因为用了 redis 缓存，第一次请求就能命中，然后不会继续执行后续插件的，也就是 ipset 也不会执行。

**Comment by PHCSJC** [comment]
可以通过修改配置来解决这个问题吗？

**Comment by IrineSistiana** [comment]
cache 和 ipset 不要放在同一个 sequence 里。

**Comment by PHCSJC** [comment]
那分流的那个配置要怎么修改呢？

  - tag: main_sequence
    type: sequence
    args:
      exec:

        - hosts

        - _prefer_ipv4

        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain
            - _return               # 返回。不再执行后续插件。

        - mem_cache

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - _return

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - ipset
            - _return

        # 剩下的未知域名用 IP 分流。原理类似 ChinaDNS，但更稳定。
        # 详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - forward_local     # 本地服务器为主。
            - if:
                - '!response_has_local_ip'  # 过滤掉非本地的 IP。
              exec:
                - _drop_response
          secondary:
            - forward_remote
            - ipset
          fast_fallback: 200  # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。单位: 毫秒。
          always_standby: true

**Comment by IrineSistiana** [comment]
没什么好办法。ipset 跟外部缓存配合不来。

**Comment by PHCSJC** [comment]
在缓存里加上是否添加ipset的标记？如果有标记，就再加一次ipset，这样可行吗？

**Comment by PHCSJC** [comment]
如果命中缓存，就跳过ipset，其实还有一个问题，即使不用redis：

如果ipset里设置了timeout，某个ip超时没有了，但是mosdns的缓存还有，那就不会再次添加到ipset里

**Comment by IrineSistiana** [comment]
框架限制，改变不了什么。

只要用ttl插件把ttl限制的比ipset的timeout小就不会出现这些问题。

**Comment by PHCSJC** [comment]
你的mosdns非常好用，没有大佬解决不了的，我等着大佬解决

**Comment by fcying** [comment]
遇到了一样的问题. 
能不能加个插件用来打标签?
如果碰到要写ipset的 就标签设1, 不需要写的就设0. 
在流程的最后, 判断标签是1就写ipset.

**Comment by PHCSJC** [comment]
请问大佬，v4.0解决这个问题了吗？

> 框架限制，改变不了什么。
> 
> 只要用ttl插件把ttl限制的比ipset的timeout小就不会出现这些问题。
