### ISSUE TITLE
怎么避免某个ip被加入到ipset？

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#340]
我的vps ip被加入到ipset里了，导致代理不通，如何避免这个ip被加入到ipset里呢？

场景是这样：vps是代理也是我的网站（所以有域名），而这个域名刚好在geosite的已知国外域名中，导致我自己只要一访问自己的网站，ip就被加到ipset里了，所以我想把我的ip排除在外，怎么排除呢？

另外，我不想通过域名的方式来排除，因为域名不固定，所以用ip来排除最合适，请问如何排除呢？感谢！

**Comment by PHCSJC** [comment]
也就是这个地方怎么修改呢？里面还可以嵌套if吗？如果能嵌套，是不是，当不执行ipset，同时也不执行_return了？

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - ipset
            - _return

**Comment by xcf13363175** [comment]
之前也碰到了这个问题，加个host可解决

**Comment by PHCSJC** [comment]
> 之前也碰到了这个问题，加个host可解决

你是指“ip 域名”这样的吗？如果域名不固定怎么办呢？

**Comment by xcf13363175** [comment]
可以自己做一个白名单，里面内容走local

**Comment by PHCSJC** [comment]
@xcf13363175 能分享下配置吗？实在不会，非常感谢！
