### ISSUE TITLE
[Feature request]可否更加个性化得配置ttl

### ISSUE THREAD

**Issue by linusdrop** [IrineSistiana/mosdns#342]
类似overture中的domainTTLFile，应用场景大概是针对那些可能会频繁改变ip的域名进行一些个别处理。比如全局配置了lazy_cache延长了ttl，但家里的ddns域名想要频繁查询是否有变动并及时更新到缓存里，反而想让ttl尽可能得低。不知道是否容易实现，或者有其他方式来实现？谢谢！

**Comment by IrineSistiana** [comment]
自定义一个域名匹配器。

配合 if 让这些域名被区别对待。
