### ISSUE TITLE
[Feature request] 允许 _prefer_ipv4 和 _prefer_ipv6 在转发插件后使用

### ISSUE THREAD

**Issue by Potat0000** [IrineSistiana/mosdns#344]
希望能在本地/远程域名分流时，仅对远程域名使用 _prefer_ipv4，而这就需要在转发插件后使用该预初始化插件。
或者，是否有可能能在获取到解析后，如果发现双栈则丢弃 AAAA 记录？
感谢！

**Comment by IrineSistiana** [comment]
请仔细看wiki的示例
