### ISSUE TITLE
[Feature request] fast_forward 指定 interface

### ISSUE THREAD

**Issue by ghost** [IrineSistiana/mosdns#347]

**Comment by IrineSistiana** [comment]
暂不考虑支持从特定 `interface` 连接上游。不可靠。

建议用 route table。

**Comment by arm64-v9a** [comment]
> 暂不考虑支持从特定 `interface` 连接上游。不可靠。
> 
> 建议用 route table。

~~改路由表太麻烦了~~，那请问  `socks5` 参数有计划支持 UDP 转发吗

**Comment by IrineSistiana** [comment]
没有。建议用 TCP
