### ISSUE TITLE
[Feature request]就说docker现在还是v3.9还没更新v4.0

### ISSUE THREAD

**Issue by williamcanon1** [IrineSistiana/mosdns#369]
**希望添加的功能**
就说docker现在还是v3.9还没更新v4.0
![image](https://user-images.githubusercontent.com/95892193/173726716-2a32562a-b226-4a62-a5a8-56472de81315.png)

**Comment by LitCcc** [comment]
现在v4.0.0还在alpha阶段，应该要等到正式版才会更新
