### ISSUE TITLE
[Feature request] 一个小提议

### ISSUE THREAD

**Issue by 0xffffharry** [IrineSistiana/mosdns#376]
**希望添加的功能**

1. 客户端行为设置，比如 192.168.1.20 正常解析， 192.168.1.21 丢弃 AAAA，192.168.1.22 丢弃 A

**Comment by IrineSistiana** [comment]
?

**Comment by 0xffffharry** [comment]
> ?

就是根据不同客户端来源ip回复不同结果，比如仅针对某个客户端丢弃aaaa解析。adguardhome有这个功能

**Comment by IrineSistiana** [comment]
query_matcher 能实现。已经有了。
