### ISSUE TITLE
[Feature request] 亲弄个直接代码或者脚本吧，我想开发个dns服务器，自定义一些功能

### ISSUE THREAD

**Issue by aogg** [IrineSistiana/mosdns#38]
**希望添加的功能**

如题

**Comment by aogg** [comment]
可执行插件: 实现 ExecutablePlugin 接口。

https://github.com/IrineSistiana/mosdns/wiki/AddNewPlugin

这样子？

**Comment by IrineSistiana** [comment]
我没理解你想干什么。
