### ISSUE TITLE
[BUG] 4.0正式版_single_flight报错

### ISSUE THREAD

**Issue by capxax** [IrineSistiana/mosdns#382]
- tag: main_sequence
    type: sequence
    args:
      exec:
        
        - _no_ecs
        - mem_cache
       - _single_flight
报错 
fatal	coremain/run.go:102	mosdns exited	{"error": "failed to init plugin #9, cannot build sequence: invalid cmd at #2: can not find execuable _single_flight

**Comment by capxax** [comment]
好吧 。。看到 移除了。。  wiki中还有

**Comment by IrineSistiana** [comment]
嗯，wiki 可能没保存成功。
