### ISSUE TITLE
[Feature request]会加入QPS限制么

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#384]
**类似dnsproxy里的ratelimit**

限制单个用户的QPS，主要是担心做公共DNS后遇到攻击，或者作者有什么更好的解决方案可以预防攻击问题么？

另外还有一个问题，我看到新发布的4.0版本，但在wiki中找不到Include参数了，配置文件是否还支持include其它配置文件？

**Comment by IrineSistiana** [comment]
无计划。如果有人想 ddos，个人怎么防都没用。~mosdns曾经有限速功能只不过理想很丰满现实很残酷~。

include 留意版本。
