### ISSUE TITLE
[Feature request] Get back ${{ }} evaluation

### ISSUE THREAD

**Issue by laggardkernel** [IrineSistiana/mosdns#389]
希望 4.x 能添加回来。`${{ }}` 属于服务端配置，执行配置的文件内容，配置者已经知道自己在做什么。又不是拿“用户输入”求值，感觉没必要这么小心。

**Comment by IrineSistiana** [comment]
主要原因是v4版换了配置文件的加载方式。基本上是调用的其他包实现的。这个功能不好加。

需要生成配置的话，linux 里搞个启动脚本 + `sed` 一把梭难度 + 模板配置，难度也不高。

**Comment by laggardkernel** [comment]
这是个思路，还可以改进为配合网络变化更新。我想到了另外一种方式，另起一个 v3 版本的 mosdns 来利用 `${{}}`。
