### ISSUE TITLE
[Bug] timeout参数报错

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#395]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.0

### 操作系统

centos

### Bug 描述和复现步骤

  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "223.5.5.5"
        - addr: "119.29.29.29"
      timeout: 2

4.0版本当按照wiki示例加入timeout参数后，启动会报错

fatal	v4/main.go:48	mosdns exited, failed to init plugin #10, unable to decode plugin args: 1 error(s) decoding:
* '' has invalid keys: timeout

**目前发现，应该是fast_forward模块没有timeout参数，这个参数应该是forward模块的，去掉就没有报错了
WIKI上相关部分写有timeout参数**

**另外想知道fast_forward的timeout由什么参数来控制？**

**Comment by IrineSistiana** [comment]
自动控制。主要是根据server的timeout设置。

Wiki 确实错了。
