### ISSUE TITLE
[Feature request]_response_valid_answer功能的建议

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#397]
因为包含一些建议，所以发到这里了

’**_response_valid_answer**
想了解一下这个功能的原理，看起来可以解决污染问题。

_response_valid_answer的解释为：应答包含有效的 ANSWER 记录 (ANSWER 中有记录能与 QUESTION 对应)

看到WIKI配置模板中最后的处理逻辑

            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response

我理解这里的处理逻辑是：
默认使用本地DNS解析，
非本地IP 且 应答包含有效应答记录的，会丢弃掉，
交给远程DNS处理；

但之前提过一种特殊情况的域名，即指向IP在境外但又不对境外DNS开放，这类域名在请求DNS过程中，
例如 2311.host: No response from server 这个域名就会出现这样的结果。

2311.host 这个域名，使用本地DNS是可以解析出结果的，只有使用远程DNS时才没有结果。

我认为是(! response_has_local_ip)判断导致2311.host使用远程DNS解析导致的，但这个域名为什么也会出现在[_response_valid_answer]的范围内？

另外不知道可否优化这个插件，处理这类特殊情况。

**Comment by IrineSistiana** [comment]
> 但这个域名为什么也会出现在[_response_valid_answer]的范围内？

"(! response_has_local_ip) && [_response_valid_answer]" 是判断 local 应答的。 local 应答有对应 ip 而且是境外 IP段。

> 另外不知道可否优化这个插件，处理这类特殊情况。

~用 fallback 。~

**Comment by IrineSistiana** [comment]
用 fallback 存在被污染的可能。像这种特殊情况不如白名单处理。

**Comment by realconnor** [comment]
更新到新版还有点懵圈，请问既然_response_valid_answer表示“答有所问”，那反过来理解，上述配置的意思是“本地IP应答”或“答非所问”都接受，前者好理解，后者对应什么情况😧？以及非IP有效应答，比如cname也丢弃吗？
