### ISSUE TITLE
[Bug] centos7下，安装服务不生效

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#401]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.1

### 操作系统

centos

### Bug 描述和复现步骤

安装服务出错，应该是工作目录定位的问题，贴一个我自己的服务脚本，可以正常运行

另外建议服务安装不要集成在二进制程序里，平台太多，维护起来会有很大问题

作者可以参考下 https://oneinstack.com/install/ 的思路

oneinstack里面的脚本部署web环境很方便，我建议把服务安装制作成shell脚本，当哪个平台不能工作了，熟悉自己平台的人，大家都可以向你提交自己熟悉平台的服务脚本

因为安装服务只是对于没有运维经验的小白有用，对小白而言，使用脚本和使用二进制程序的命令安装服务，只是复制粘贴的命令不同而已，作者可以考虑下，看到你之前取消掉服务安装，应该头疼的就是这种问题。

### 使用的配置文件

```yaml
[Unit]
Description=mosdns
After=network.target

[Service]
ExecStart=/usr/local/bin/mosdns start -c config.yaml -d /etc/mosdns
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by IrineSistiana** [comment]
> 服务安装制作成shell脚本

现有的服务命令是调用别人的包实现的。能力有限，搞不动。欢迎 pr。

**Comment by cresky-github** [comment]
在Openwrt安装时，也是一样的问题。
总是装不上。
看来，还是得把安装、卸载之类的脚本化。

**Comment by cresky-github** [comment]
> > 服务安装制作成shell脚本
> 
> 现有的服务命令是调用别人的包实现的。能力有限，搞不动。欢迎 pr。

貌似
as-service参数无效

我用命令行启动

**Comment by IrineSistiana** [comment]
@cresky-github Openwrt 不支持。

as-service 是系统服务管理程序调用 mosdns 加的。不能用在命令行。

**Comment by cresky-github** [comment]
> @cresky-github Openwrt 不支持。
> 
> as-service 是系统服务管理程序调用 mosdns 加的。不能用在命令行。

哦，原来如此。
所有的命令参数，help都显示了吗？

看来，得自己写服务启动脚本了。

**Comment by cresky-github** [comment]
> @cresky-github Openwrt 不支持。
> 
> as-service 是系统服务管理程序调用 mosdns 加的。不能用在命令行。


Openwrt 的启动脚本已经搞定了

**Comment by sbwml** [comment]
> 
**送你个openwrt luci ipk包**
https://github.com/sbwml/luci-app-mosdns/releases

**小白用预设**
![1](https://user-images.githubusercontent.com/16485166/178160460-0b29bc7e-98e5-4630-a5d5-4f4c07d3f42a.png)
![2](https://user-images.githubusercontent.com/16485166/178160258-01e43895-6952-4c62-a27c-261c360a29bd.png)

**进阶大佬用自定义**
![3](https://user-images.githubusercontent.com/16485166/178160274-d07425d3-6f82-49c7-b353-1628a36965d9.png)

**Comment by sbwml** [comment]
> ### 在提交之前，请确认
> * [x]  我已经尝试搜索过 Issue ，但没有找到相关问题。
> * [x]  我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
> * [x]  我仔细看过 wiki 后仍然无法自行解决该问题。
> * [x]  我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)
> 
> ### mosdns 版本
> 4.1
> 
> ### 操作系统
> centos
> 
> ### Bug 描述和复现步骤
> 安装服务出错，应该是工作目录定位的问题，贴一个我自己的服务脚本，可以正常运行
> 
> 另外建议服务安装不要集成在二进制程序里，平台太多，维护起来会有很大问题
> 
> 作者可以参考下 https://oneinstack.com/install/ 的思路
> 
> oneinstack里面的脚本部署web环境很方便，我建议把服务安装制作成shell脚本，当哪个平台不能工作了，熟悉自己平台的人，大家都可以向你提交自己熟悉平台的服务脚本
> 
> 因为安装服务只是对于没有运维经验的小白有用，对小白而言，使用脚本和使用二进制程序的命令安装服务，只是复制粘贴的命令不同而已，作者可以考虑下，看到你之前取消掉服务安装，应该头疼的就是这种问题。
> 
> ### 使用的配置文件
> ```yaml
> [Unit]
> Description=mosdns
> After=network.target
> 
> [Service]
> ExecStart=/usr/local/bin/mosdns start -c config.yaml -d /etc/mosdns
> Restart=on-abort
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> ### mosdns 的 log 记录
> _No response_

+1  其实只需要一个简单shell，即可全发行版部署

**Comment by jinwyp** [comment]
https://github.com/jinwyp/one_click_script/blob/master/DNS.md#mosdns

全平台安装脚本

**Comment by IrineSistiana** [comment]
@jinwyp @sbwml 

如果不介意的话，我可以把链接放在 mosdns 的 wiki 里。

请另开一个 issue 然后

项目名:
链接:
一段话简介:

**Comment by jinwyp** [comment]
> @jinwyp @sbwml
> 
> 如果不介意的话，我可以把链接放在 mosdns 的 wiki 里。
> 
> 请另开一个 issue 然后
> 
> 项目名: 链接: 一段话简介:

建议你先弄个置顶的帖子issue 把格式定好 以后其他做安装脚本的人 按照格式回复issue 就可以了 

这样其他人就更容易看到

**Comment by sbwml** [comment]
> @jinwyp @sbwml
> 
> 如果不介意的话，我可以把链接放在 mosdns 的 wiki 里。
> 
> 请另开一个 issue 然后
> 
> 项目名: 链接: 一段话简介:

当然可以，只是文化水平太低，不会写描述
