### ISSUE TITLE
[Feature request] arbitrary 从外部数据载入记录

### ISSUE THREAD

**Issue by jellybean13** [IrineSistiana/mosdns#415]
**希望添加的功能**

在 3.x, arbitrary 被移除之前, arbitrary 支持从外部数据导入记录.
4.x, arbitrary 目前无法从外部数据导入记录, 这会导致配置文件与自定义记录产生耦合问题.

可以利用 data_providers 加载外部数据, arbitrary 读取 data_providers 的数据以实现此功能.

**Comment by pptom** [comment]
其实也想知道，有木有可能从redis或者其他地方直接加载数据？
用于判断域名是否在某个列表中。

**Comment by urlesistiana** [comment]
v5 支持外部数据导入记录。
