### ISSUE TITLE
[Feature request]关于ECS的优化建议

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#416]
**ECS适当保护隐私**

不确定现在的ECS插件机制是怎样的，因为在wiki的案例中，看到强制替换的IP写的是1.2.3.4，而不是1.2.3.0

请问ECS当开启了从来源取IP，向上游DNS传送的也是来源地址的IP么，还是将最后一位变成 0 处理的？

例如：

来源地址是1.2.3.4，那么向上游DNS的传送的IP是1.2.3.4/24，还是1.2.3.0/24？

如果是前者，是否可以加个优化，自动将ECS上传IP的最后一位变成0，或者现在的插件有什么办法能实现这个需求？

**Comment by IrineSistiana** [comment]
这个只要你抓包看一下就能发现 mosdns 会自动 mask ip 。
