### ISSUE TITLE
[Feature request]akamai的CDN貌似不支持EDNS0

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#425]
在服务器上做ECS测试时发现的问题，部分域名不会根据ECS的子网信息，分配距离ECS子网IP较近的CDN节点

例如，我的DNS服务器部署在香港，使用美国的服务器去查询时，绝大部分域名，可以准确的返回美国的CDN节点，说明ECS生效了

但akamai的CDN，不知道是什么原因，会返回距离出口DNS，也就是距离我香港DNS服务器较近的CDN节点，所以当我用美国的服务器访问使用akamaiCDN的域名时

例如
dig www.microsoft.com @dns.ip +subnet=x.x.x.0/24  （x.x.x.0/24  是美国的子网IP）

则会返回香港的CDN节点，而不是美国的节点，我测试了一下，应该不光是mosdns有这个问题，dnsproxy这些都是一样的

对DNS的技术没有深入研究过，想知道这是什么原因造成的，是否有办法优化，让ECS信息对AKAMAI这类CDN生效

**Comment by IrineSistiana** [comment]
ECS只是传达客户IP给各个NS服务器的协议。如果域名的NS服务器，比如你说的akamai，不看ECS，只看请求的来源IP，那一点办法都没有。
