### ISSUE TITLE
[Feature request]希望增加一个类似smartdns的最快IP功能

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#433]
目前看来，一些不会根据ECS调整位置的NS服务器，会错误将一些没用大陆CDN节点的域名解析到离大陆更远的地方，对于这种域名的处理，最简单的办法，就是指向台湾或日本的DNS查询，这样可以获取到延迟非常低的大陆周边CDN，github.com就是一个典型的例子

但如果手动来优化，这个成本太高了，功能大概的设计思路：

1、向DNS-TAG1与DNS-TAG2同时查询，用TAG而不是直接用IP的原因是为了加ECS
2、加入IP筛选，如果命国内IP，则优先国内的，不然丢弃
3、如果命中非国内的IP，对比返回的多个IP，选择ping最快的IP

不知道可否实现

**Comment by sbwml** [comment]
如果没有记错的话   v3 版本应该能满足你的需求，v3 版本包含 adguard home 的 “最快 ip地址” 模块，```fastest_ip: ture```

这个功能在v4中被弃用，也许是太过于鸡肋。等待所有上游响应ip 再ping ，最后得到ip的耗时怕是要正常的数倍了

**Comment by IrineSistiana** [comment]
不完全是鸡肋。这功能是有实际意义的。

v4 去掉主要原因是探测过程麻烦而且耗时。不适合实时请求。导致绝大部分个人用户开启这功能其实都是debuff。

不实时探测的方法。目前想到的。比如类似 lazy cache 的机制。第一个请求的应答不变，延时执行探测。第二个请求后应答就是优化的。

**Comment by luzhaohui** [comment]
smartdns 默认配置就返回一个最快 IP，看似很美妙，实际使用下来，带来了太多问题。
（也可能是我不太会用，但还是果断放弃了）

**Comment by mark-syctnet** [comment]
@IrineSistiana 
有一个这样的需求可能要用的这个功能. 或是有没有其它的方法来解决:
   1.有个2个地方A和B , A与B之间有专线互联了, A和B各地都有自己的MOSDNS做DNS服务器.
   2. A和B都有各有2台服务器(A:192.168.10.2, 和B:192.168.110.2) ,2个服务器之间都做出同步.
   3.A和B的人员都需要访问一个域名: www.COM 并且这个这个域名同时指向(192.168.10.2和192.168.110.2)
   4. 要求是A和B的人员访问www.COM 优先使用本地的服务器,同时有一服务器坏了.可以使用另一方的的服务器.
   
我现在想的方法就是 各地通过fastest_ip的判断方式. A和B的人员返回不同的结果给用户的方式来实现.

**Comment by christaikobo** [comment]
是不是可以保留这个功能
个人用户开这个是debuff的话，可以wiki推荐个人不开启？

**Comment by daiaji** [comment]
@terrytw 那四舍五入不是根本没人用。

**Comment by urlesistiana** [comment]
无计划。

“自动使用延时最低的IP”这个功能看上去很美好。但实际上没作用。大 CDN 已经帮你把网络优化到极限了。烂的 CDN 即使你自动选择了延时低的接入点，线路差，该多慢还是多慢。延时不能说明速度。

四舍五入真的没什么用。
