### ISSUE TITLE
[Feature request]缓存有没有可能存放到mysql，redis等外部存储中

### ISSUE THREAD

**Issue by mkanako** [IrineSistiana/mosdns#44]
好处有二
1.重启缓存不失效
2.我可以自己写定时脚本查缓存，把那些块过期的，预先去查询进而更新缓存，这样当真有查询过来可以快速直接返回结果
总之这样能让我获得一种动态控制返回结果的能力

**Comment by IrineSistiana** [comment]
可以是可以，但是没有必要吧....

你这打算用在多大规模上？

**Comment by mkanako** [comment]
@IrineSistiana 
其实我就是自用而已，只能说有了这个更加灵活，可以进行更多样的玩法，比如：我可以对缓存数据做各种统计分析~~~

要是作为对外公开的dns服务的话那这个就很有必要

**Comment by mkanako** [comment]
比方还有这种场景，我想临时屏蔽某个域名，那我直接在缓存添加相应的域名和返回结果就好了

不然的话，我得改配置重启服务(这还导致缓存失效)，多麻烦多不好

**Comment by mkanako** [comment]
突然想到要是hosts插件能支持从数据库中读数据，也能解决上面那种场景，哈哈😁

**Comment by IrineSistiana** [comment]
cache 后面接 mysql 太麻烦了，暂不考虑自带。redis 可行。

**Comment by IrineSistiana** [comment]
感谢建议。cache 支持 redis 了。
