### ISSUE TITLE
[Feature request]增加一个插件记录DNS请求者IP，请求的域名，请求时间

### ISSUE THREAD

**Issue by muziling** [IrineSistiana/mosdns#444]
**希望添加增加一个插件记录DNS请求者IP，请求的域名，请求时间**

使用场景： 查看孩子在访问哪些网站。

功能有点类似nginx的log format参数，可以自定义日志格式

**Comment by IrineSistiana** [comment]
建议前置一个 adguard home 或者类似的dns 私人服务器。

mosdns 暂不考虑增加这个功能。没必要造轮子。
