### ISSUE TITLE
[Feature request]建议增加mips64版本

### ISSUE THREAD

**Issue by carrionlee** [IrineSistiana/mosdns#45]
这样可以用在edgerouter上 😃️

**Comment by IrineSistiana** [comment]
曾经有过，但我好像之前 mips64 哪个版本有问题来着。我没设备没法测试。

你可以把根目录的 `release.py` 前头关于 `mips64` 的注释去掉，然后 `python release.py` 编译，试试 mips64 架构能正常使用么。

https://github.com/IrineSistiana/mosdns/blob/62c89ad2ebae8df7b79a0df4eb58aa752fd27551/release.py#L29-L32

**Comment by carrionlee** [comment]
我是外行，google了一下，从源码重新编译了下
`GOOS=linux GOARCH=mips64 go build`
编译后，在edgerouter-4上能用

**Comment by IrineSistiana** [comment]
看来没问题了。

**Comment by IrineSistiana** [comment]
reopen

下次 release 前备忘。
