### ISSUE TITLE
[Bug] fast_forward日志err比率太高了

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#453]
配置：
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: tls://223.5.5.5:853
          enable_pipeline: true

        - addr: tls://120.53.53.53:853
          enable_pipeline: true

第1个正常，第2个err太多，按文档意思是没有返回，这没返回的比率也太高了，把pipeline关了也一样，换成腾讯DoH的也一样，甚至换成UDP err都非常高，fast_forwad对于腾讯DNS的适配有问题？

日志：

    "forward_local": {
      "0": {
        "err": 27,
        "latency": {
          "avg": 10,
          "max": 125,
          "min": 4,
          "p25": 5,
          "p50": 5,
          "p75": 6
        },
        "query": 266
      },
      "1": {
        "err": 234,
        "latency": {
          "avg": 91,
          "max": 477,
          "min": 7,
          "p25": 8,
          "p50": 30,
          "p75": 178.25
        },
        "query": 266
      }

**Comment by IrineSistiana** [comment]
https://github.com/IrineSistiana/mosdns/issues/428
