### ISSUE TITLE
建议增加域名预读取的功能

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#454]
smartdns有个参数是prefetch-domain，解释如下：

通过 prefetch-domain yes 来启用域名预先获取功能，提高查询命中率。配合上述 TTL 超时时间，SmartDNS 将在域名 TTL 即将超时时，再次发送查询请求，并缓存查询结果供后续使用。频繁访问的域名将会持续缓存。此功能将在空闲时消耗更多的 CPU。

这个功能可以解决有些域名的IP总是变化的问题，IP频繁变化导致mosdns的lazy_cache返回的其实是已经失效的IP了，而这个功能就可以解决这个问题，至于哪些域名IP频繁变化，比如：www.rfi.fr

**Comment by IrineSistiana** [comment]
无计划。unbound 的 预读取 功能设计的非常完美。可控性也很高。有相关需求建议前置一个 unbound。

**Comment by PHCSJC** [comment]
还是希望mosdns可以实现，毕竟2个DNS很奇怪，出问题的概率也更高
