### ISSUE TITLE
[BUG]mos-chinadns升级至此需要改哪里？

### ISSUE THREAD

**Issue by ghost** [IrineSistiana/mosdns#47]
**出现了什么问题**
mos-chinadns 迭代至此不会用了，请问用原来的luci -app-mos-chinadns壳，换上这里的二进制核心，再用示例.yaml覆盖原来的config,就可以直接替换使用吗？

```txt

```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：

使用的启动参数或启动方式：

操作系统和平台：

进行了什么操作导致了问题的出现：

使用的配置文件：

```yaml

````

**Comment by IrineSistiana** [comment]
我没有维护过 luci -app-mos-chinadns。你说的这个 luci 界面不是我做的。所以我不清楚。

**Comment by ghost** [comment]
用的是这个https://github.com/QiuSimons/openwrt-packages/branches/main/luci-app-moschinadns
您能自主研发个luci吗？实用性更好

**Comment by IrineSistiana** [comment]
不好意思,水平有限
