### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by yeezylife** [IrineSistiana/mosdns#483]
deleted

**Comment by BozhanL** [comment]
```202.103.44.150``` 这个地址能用吗? 我这不行
```
$ sudo dig @202.103.44.150 baidu.com

; <<>> DiG 9.16.27-Debian <<>> @202.103.44.150 baidu.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by yeezylife** [comment]
> `202.103.44.150` 这个地址能用吗? 我这不行

C:\Users\xxx>ping 202.103.44.150

正在 Ping 202.103.44.150 具有 32 字节的数据:
来自 202.103.44.150 的回复: 字节=32 时间=7ms TTL=58
来自 202.103.44.150 的回复: 字节=32 时间=8ms TTL=58
来自 202.103.44.150 的回复: 字节=32 时间=7ms TTL=58
来自 202.103.44.150 的回复: 字节=32 时间=7ms TTL=58

这个就是电信的dns啊 我forward_local用的这个

**Comment by BozhanL** [comment]
> > `202.103.44.150` 这个地址能用吗? 我这不行
> 
> C:\Users\xxx>ping 202.103.44.150
> 
> 正在 Ping 202.103.44.150 具有 32 字节的数据: 来自 202.103.44.150 的回复: 字节=32 时间=7ms TTL=58 来自 202.103.44.150 的回复: 字节=32 时间=8ms TTL=58 来自 202.103.44.150 的回复: 字节=32 时间=7ms TTL=58 来自 202.103.44.150 的回复: 字节=32 时间=7ms TTL=58
> 
> 这个就是电信的dns啊 我forward_local用的这个

你用这个命令试试 ```nslookup baidu.com 202.103.44.150```

**Comment by yeezylife** [comment]
> 

C:\Users\xxx>nslookup baidu.com 202.103.44.150
服务器:  UnKnown
Address:  202.103.44.150

非权威应答:
名称:    baidu.com
Addresses:  39.156.66.10
          110.242.68.66

能用啦 还挺快。。。

**Comment by BozhanL** [comment]
看起来是正常的.
```
2022-09-14T11:51:22.051+0800	debug	bundled_upstream/bundled_upstream.go:70	response received	{"query": "zjg2.ssrfree2.xyz. IN AAAA 22 34 ::1", "from": "202.103.44.150"}
```
一般能用就可以不管 ```debug``` 信息
