### ISSUE TITLE
发现改版了，请问现在程序的作用是什么呢？

### ISSUE THREAD

**Issue by chinaniupai** [IrineSistiana/mosdns#5]
还是像以前那样为了无污染吗？还是改成了其他作用？

**Comment by christaikobo** [comment]
作者似乎想要把重构后的项目做成类似于smartdns的全能dns分流器，彻底替代dnsmasq

对于不太懂的人来说，目前直接用原来的就可以，性能没有变化，也没有修复什么bug
原来的repo还在的：https://github.com/IrineSistiana/mos-chinadns

如果有去广告，EDNS，域名分流之类的需求，可以考虑切换至新版
新版似乎还在快速迭代，目前还不稳定，建议等个个把月再说

**Comment by IrineSistiana** [comment]
@terrytw 

> 做成类似于smartdns的全能dns分流器，彻底替代dnsmasq

真正的计划远没这么宏伟 (lll￢ω￢)

当时只是希望更直观灵活的实现多地区链式分流。好像只有 mos-chinadns 有这个功能。因为单靠域名分流的不准，新出现的域名必错，单靠并发 IP 分流存在竞争问题。

插件化原来的分流功能，发现换个执行顺序就可以变成去广告屏蔽bogus IP什么的，纯属`意外得到的`功能，之前从未考虑过....

确实，原 repo 更人性化一点，能直接用。mosdns的配置难度有点高。而且估计降不下来。因为配置插件执行顺序必须要了解点 DNS 知识。

**Comment by douglas-lee** [comment]
> @terrytw
> 
> > 做成类似于smartdns的全能dns分流器，彻底替代dnsmasq
> 
> 真正的计划远没这么宏伟 (lll￢ω￢)
> 
> 当时只是希望更直观灵活的实现多地区链式分流。好像只有 mos-chinadns 有这个功能。因为单靠域名分流的不准，新出现的域名必错，单靠并发 IP 分流存在竞争问题。
> 
> 插件化原来的分流功能，发现换个执行顺序就可以变成去广告屏蔽bogus IP什么的，纯属`意外得到的`功能，之前从未考虑过....
> 
> 确实，原 repo 更人性化一点，能直接用。mosdns的配置难度有点高。而且估计降不下来。因为配置插件执行顺序必须要了解点 DNS 知识。

哈哈，感觉mosdns的功能就是我心目中要的，多地区智能分流。实际使用过程中，虽然mos-chinadns也很好了，但还是有少许逻辑性的问题，mosdns的实现原理上是解决了的，还在试用中，感谢作者。

**Comment by fox85** [comment]
特此来回复。支持作者~~~~

**Comment by chinaniupai** [comment]
> @terrytw
> 
> > 精心设计的smartdns的全能dns分流器，彻底替代dnsmasq
> 
> 真正的计划远没这么宏伟（lll￢ω￢）
> 
> 当时只是希望更直观灵活的实现多地区链式分流。好像只有mos-chinadns有这个功能。因为单靠域名分流的不准，新出现的域名必定错，单靠并发IP分流存在竞争问题。
> 
> 插件化原来的分流功能，发现换个执行顺序就可以变成去广告屏蔽bogus IP什么的，纯属`意外得到的`功能，之前从未考虑过...。
> 
> 确实，原repo更人性化一点，能直接用。mosdns的配置稍微有点高。而且估计降不下来。因为配置插件执行顺序必须要了解点DNS知识。

想拜托作者可以弄个自动配置版，就像原来的mos-chinadns一样打开直接就能用。给小白用户一个机会

**Comment by IrineSistiana** [comment]
@chinaniupai 

> 像原来的mos-chinadns一样打开直接就能用

估计是不可能了。mos-chinadns有预设配置是因为mos-chinadns功能有限。而mosdns的功能全靠用户DIY。

简单的教程可能会有。等 mosdns 配置文件不再变的时候。我觉得v0.15.0版后配置应该不会再改了。已经全变成插件了没什么改动的空间了。

**Comment by kuyagic** [comment]
有没有考虑加上 cache 功能 ? 如果短期内没有计划 只能考虑前面放一个 dnsmasq 了 (
@IrineSistiana

**Comment by IrineSistiana** [comment]
@kuyagic 没有考虑。

---

顺便说一下我对 cache 的感觉:

如果用户很少，很可能不需要 cache，因为

- 请求量很小，密度低，cache 的命中率很低。
- 上游都有  cache，所以即使本地配置了 cache ，即使运气好命中了，也只能节约 10ms 时间。效果微微微微微乎其微。

请求量大的时候，用递归解析的时候， cache 才有效果。

虽然很多 dns 软件都提供内置的 cache，但实现普遍没有 unbound dnsmasq 这类软件的 cache 严谨高效。特别是大流量的时候。

所以如果希望用 cache，追求极致性能，最好的方法就是用专业软件。

**Comment by douglas-lee** [comment]
> @kuyagic 没有考虑。
> 
> 顺便说一下我对 cache 的感觉:
> 
> 如果用户很少，很可能不需要 cache，因为
> 
> * 请求量很小，密度低，cache 的命中率很低。
> * 上游都有  cache，所以即使本地配置了 cache ，即使运气好命中了，也只能节约 10ms 时间。效果微微微微微乎其微。
> 
> 请求量大的时候，用递归解析的时候， cache 才有效果。
> 
> 虽然很多 dns 软件都提供内置的 cache，但实现普遍没有 unbound dnsmasq 这类软件的 cache 严谨高效。特别是大流量的时候。
> 
> 所以如果希望用 cache，追求极致性能，最好的方法就是用专业软件。

支持作者的看法，个人使用，请求量很低，且快那么几十ms根本无感知，大多数实际使用过程中的体验，cache不仅起不到任何作用，甚至有时候还会带来副作用，比如自己的某个域名更新了ip，但是因为有cache，要导致重启服务才能解决。

**Comment by christaikobo** [comment]
结果最终还是加上了cache和hosts，哈哈，就是要替代dnsmasq的dns功能呀

**Comment by IrineSistiana** [comment]
关于 cache，我之前说片面了。

> 如果用户很少，很可能不需要 cache，因为请求量很小，密度低，cache 的命中率很低。

原因是现在的系统内都自带 DNS 缓存。软件也自带，比如 Chrome。所以绝大部分场景根本轮不到本地 cache 发挥作用。

但是，有些软件就比较“特立独行”，不用系统缓存，自己也没有缓存。导致每次连接域名前都请求一次 DNS。如果是延时高的远程服务器，这个速度下降就让人头大了。这时候配置一个 cache 就有用了。

所以 mosdns 加了个 cache。没有什么魔法功能。随用随插。

**Comment by chinaniupai** [comment]
> 关于缓存，我之前说片面了。
> 
> > 如果用户很少，很可能不需要缓存，因为请求量很小，密度低，缓存的命中率很低。
> 
> 原因是现在的系统内部都自带DNS缓存。软件也自带，例如Chrome。所以绝大部分场景根本轮不到本地缓存发挥作用。
> 
> 但是，有些软件就比较“特立独行”，不用系统缓存，自己也没有缓存。导致每次连接域名前都请求一次DNS。如果是延迟高的远程服务器，这个速度下降就有人头大了。这时候配置一个cache就有用了。
> 
> 所以mosdns加了个cache。没有什么魔法功能。随用随插。

请问，现在的mosdns的抗污染能力如何？

最头疼的就是绝大多数速度较快的外国doh用不了，像谷歌或者9.9.9.9这些似乎都被屏蔽了。

**Comment by rampageX** [comment]
@chinaniupai fast_forwarder 支持通过 socks5 代理 DoT，DoH 所以不存在你说的问题。

**Comment by chinaniupai** [comment]
> @chinaniupai fast_forwarder支持通过socks5代理DoT，DoH所以不存在你说的问题。

不是人人都有socks5代理的

**Comment by terrytw** [comment]
> > @chinaniupai fast_forwarder支持通过socks5代理DoT，DoH所以不存在你说的问题。
> 
> 不是人人都有socks5代理的

你的需求就好比又要看youtube又说我不能翻墙，那只能建议你肉身出国了

**Comment by javasboy** [comment]
为什么新版本去掉了socks5代理功能呢？

**Comment by christaikobo** [comment]
请问一下作者，大版本号刷到1了，是不是配置文件稳定了，短期内没有更改计划了呢？

**Comment by IrineSistiana** [comment]
`版本号刷到1` = 能用了

> 短期内没有更改计划了呢？ 

只能说目前没有任何计划.未来会不会变,有没有新功能要加,谁知道呢.

**Comment by javasboy** [comment]
> @chinaniupai fast_forwarder 支持通过 socks5 代理 DoT，DoH 所以不存在你说的问题。

我通过socks5 使用DoH 8.8.8.8经常返回错误，使用udp 正常。不知道大家有没用遇到。

**Comment by xiaolei0125** [comment]
@IrineSistiana  非常喜欢你对mosdns进行的插件式可编程设计，灵活方便，满足多种需求场景，正在试用中，希望mosdns越来越好！

**Comment by sbilly** [comment]
这个和 coredns 有啥区别吗？coredns 的插件挺容易写的。
