### ISSUE TITLE
[Feature request] blackhole 可以配置多个 ip

### ISSUE THREAD

**Issue by aeeq** [IrineSistiana/mosdns#500]
**希望添加的功能**

比如 劫持 cloudflare cdn ip 段，返会特定的 ip ,可以配置多个

**Comment by liang-hiwin** [comment]
搞污染？

**Comment by urlesistiana** [comment]
v4.3 支持了。

**Comment by tonebean** [comment]
blackhole可配置多个ip的话，那可否支持下data_providers引入文件

**Comment by tonebean** [comment]
> v4.3 支持了。
blackhole可配置多个ip的话，那可否支持下data_providers引入文件
