### ISSUE TITLE
[Bug] 4.3版本 CPU资源占用翻倍

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#508]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.3

### 操作系统

centos

### Bug 描述和复现步骤

更新4.3版本后，发现CPU资源翻倍，是增加了什么占用CPU资源的功能么？

### 使用的配置文件

```yaml
-
```

**Comment by urlesistiana** [comment]
没有。

如果觉得有异常，请按 wiki 的 "debug 性能问题"，提交一份 pprof。
