### ISSUE TITLE
[Bug] 日志写入问题

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#523]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.x

### 操作系统

centos

### Bug 描述和复现步骤

之前有提过日志问题，然后想到了一个办法，定时用sed命令去清理指定的日志，以防止日志被刷爆，但出现了新的问题，我发现当用命令行定时处理日志后

例如：
#*/60 * * * * sed -i '/missing or invalid media type header/d' /etc/mosdns/mosdns.log

此时日志被清理部分内容，但发现之后该日志文件不再会被写入内容，奇怪的是，如果我使用debug模式的话，执行sed命令后，则可以正常写入新日志，但使用warn后，缺不会再有任何写入，是bug还是有什么处理机制？

### 使用的配置文件

```yaml
-
```

**Comment by urlesistiana** [comment]
你不能在 mosdns 运行的时候同时修改日志。并行写入，发生任何意外都不意外。

日志最好还是走 stdout或err，让守护进程去管。自动分割，打包，归档，清理。

**Comment by pmkol** [comment]
> 

有什么好的工具推荐么？

**Comment by urlesistiana** [comment]
基本上随便一个守护进程程序都自带日志管理功能吧。你说的日志过滤功能需要日志平台。

**Comment by emptyteeth** [comment]
用重定向怎么样?
```shell
mosdns start -c config.yaml >>mosdns.log 2>&1
```
也许可以加上sed
```shell
mosdns start -c config.yaml  2>&1 | sed -u 'something/d' >>mosdns.log
```
