### ISSUE TITLE
[Bug] 报错 entry returned an nil response

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#526]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.3.0

### 操作系统

centos

### Bug 描述和复现步骤

每小时总会报错几条以下信息，想知道是什么问题造成的

注：127.0.0.1是nginx反代出去的http

2022-10-12T01:28:50.462+0800	error	dns_handler/entry_handler.go:115	entry returned an nil response	{"query": "h.verify.zhimasdk.com. IN A 56051 72 ::ffff:127.0.0.1"}
2022-10-12T01:32:56.682+0800	error	dns_handler/entry_handler.go:115	entry returned an nil response	{"query": "commnat-cohort-gc.ess.apple.com. IN A 50321 635 ::ffff:127.0.0.1"}
2022-10-12T01:32:56.683+0800	error	dns_handler/entry_handler.go:115	entry returned an nil response	{"query": "commnat-main-gc.ess.apple.com. IN A 36760 632 ::ffff:127.0.0.1"}

### 使用的配置文件

```yaml
-
```

**Comment by davidtall** [comment]
same issue

**Comment by pmkol** [comment]
目前测试，发现似乎是nginx开启0RTT与HTTP3导致的，不知作者能否检查下？

目前我测试的结果是，同时开启HTTP3与0RTT，会导致每隔10分钟左右，就有以上报错
关闭HTTP3与0RTT，报错1小时未出现
关闭0RTT开启HTTP3，偶尔会有少量报错

**Comment by urlesistiana** [comment]
和 quic 应该没有关系。

这个报错是指: 插件流水线运行结束后，没有返回应答，也没有返回报错。

应该是你的流水线有问题。部分请求没有被应答就返回了。

**Comment by pmkol** [comment]
> 和 quic 应该没有关系。
> 
> 这个报错是指: 插件流水线运行结束后，没有返回应答，也没有返回报错。
> 
> 应该是你的流水线有问题。部分请求没有被应答就返回了。

看起来是0RTT的问题，目前关闭0RTT没有报错了，有办法兼容0RTT么？

**Comment by urlesistiana** [comment]
和 quic 没有直接关系。

服务端和插件处理是独立的。插件不管传输层的事。

**Comment by pmkol** [comment]
> 和 quic 没有直接关系。
> 
> 服务端和插件处理是独立的。插件不管传输层的事。

流水线问题可能是什么原因造成的呢？我前端nginx直接调用的mosdns，另外一台服务器上，也用nginx转发，就没有这个问题，只是这台开启了HTTP3

**Comment by urlesistiana** [comment]
用最新版本，开 debug log，然后贴配置。

**Comment by pmkol** [comment]
目前调整了一下nginx的配置，在观察报错情况，如果可以的话，可以提供一个nginx反代doh没报错的示例么，我看下是不是因为少什么参数？

**Comment by urlesistiana** [comment]
> 服务端和插件处理是独立的。插件不管传输层的事。

这个报错是插件端的。和传输层没有关系。

> 每小时总会报错几条以下信息

是你的流水线逻辑存在问题。或者是插件里面有数据竞争 bug 了。没配置，没有 debug log，不复现，无法定位问题。

至于 nginx 似乎和报错有关，我觉得只是概率上的意外。

**Comment by pmkol** [comment]
目前换了4.4.2，没有报错了
