### ISSUE TITLE
[Feature request] host 指定多个ip后 客户端查询 希望能随机的返回顺序

### ISSUE THREAD

**Issue by kuyagic** [IrineSistiana/mosdns#527]
**希望添加的功能**
host 指定多个ip后 客户端查询 希望能随机的返回顺序
使用场景就是 cloudflare 下 指定了一些本地比较快的ip 但是每次解析后 第一个ip都不变 希望能够随机使用指定的一系列IP地址

**Comment by urlesistiana** [comment]
用 _misc_optm 。
