### ISSUE TITLE
[Feature request]请求添加缓存预读取的功能

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#539]
lazy cache：不建议公用服务器开启。公用服务器可考虑部署“缓存预取”，比如 unbound 的 prefetch。

请求大佬在mosdns添加缓存预读取的功能，好久之前也反馈过#454，再次请求大佬发功！

简易版的就可以，在缓存快过期间时自动解析1次

**Comment by urlesistiana** [comment]
Declined. 你用了 unbound 你就知道 mosdns 的 cache 有多低效(性能，缓存率，策略，多个方面)。专业的事让专业软件干。

**Comment by PHCSJC** [comment]
@urlesistiana 不要这么说，mosdns是我用过的最牛逼的dns软件
