### ISSUE TITLE
[Bug] cannot get service status

### ISSUE THREAD

**Issue by CHANTXU64** [IrineSistiana/mosdns#541]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [ ] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.5.2-0-gcdc14af

### 操作系统

openwrt  Linux version 5.15.74

### Bug 描述和复现步骤

openwrt 中没有service，于是我复制/etc/shinit，写了/usr/bin/service，以下是/usr/bin/service的内容：
```shell
#!/bin/bash

if [ -f "/etc/init.d/$1" ]; then
    /etc/init.d/$@
else
    echo "Usage: service <service> [command]"
    if [ -n "$1" ]; then
        echo "Service "'"'"$1"'"'" not found, the following services are available:"
    else
        echo "The following services are available:"
    fi
    for F in /etc/init.d/* ; do
        printf "%-30s\t%10s\t%10s\n"  "$F" \
        $( $($F enabled) && echo "enabled" || echo "disabled" ) \
        $( [ "$(ubus call service list "{ 'verbose': true, 'name': '$(basename $F)' }" \
        | jsonfilter -q -e "@['$(basename $F)'].instances[*].running" | uniq)" = "true" ] \
        && echo "running" || echo "stopped" )
    done;
    return 1
fi
```

运行`mosdns service install`

运行`/usr/bin/service mosdns status`，结果`Stopped`

运行`mosdns service start`，结果如下：
```
2022-10-27T09:56:57.006Z	info	coremain/service.go:130	service is starting
2022-10-27T09:56:58.024Z	warn	coremain/service.go:134	cannot get service status, %wexit status 1
```

### 使用的配置文件

```yaml
/
```

### mosdns 的 log 记录
```
2022-10-27T09:56:57.013Z    info    coremain/service.go:48  starting service    {"platform": "unix-systemv"}
2022-10-27T09:56:57.013Z    info    coremain/run.go:107 working directory changed   {"path": "/usr/bin"}
```

**Comment by CHANTXU64** [comment]
我发现好像是`/etc/init.d/mosdns`中第88行的问题，输出`Stopped`后`exit 1`，导致`kardianos/service/service_unix.go`的`runCommand`函数在最后一步`isExitError`导致出错。

将`/etc/init.d/mosdns`第88行改成`exit 0`就可以避免cannot get service status

**Comment by urlesistiana** [comment]
`mosdns service` 用的 `kardianos/service` 不支持 openwrt。~~建议手写一个 init.d 脚本。~~ 项目中包含一个脚本，稍微修改一下就能用。 scripts/openwrt/mosdns-init-openwrt
