### ISSUE TITLE
v5 缺少文件自动重载

### ISSUE THREAD

**Issue by liang-hiwin** [IrineSistiana/mosdns#563]
v5 缺少文件自动重载
`auto_reload: false # 文件有变化时是否自动重载。`

**Comment by urlesistiana** [comment]
这个功能 v5 删掉了。

**Comment by xiaolei0125** [comment]
@urlesistiana   文件自动重载功能还是有很多应用场景的，例如在外面更新容器名和容器IP到hosts文件。目前还在用v4,    v5有什么替代办法吗？
