### ISSUE TITLE
[Feature request] v5 似乎没有 v4 的 ecs auto 功能

### ISSUE THREAD

**Issue by xukecheng** [IrineSistiana/mosdns#592]
**希望添加的功能**

![CleanShot 2023-01-19 at 15 09 51@2x](https://user-images.githubusercontent.com/29099863/213378013-ec6d0380-931f-4aab-bac6-31d4e828c291.png)
![CleanShot 2023-01-19 at 15 10 11@2x](https://user-images.githubusercontent.com/29099863/213378041-060fd1fa-30fa-4126-8b59-8f48b04c8305.png)

v5 似乎只支持附加 ecs，不支持自动将用户请求的来源地址作为 ECS 附加到请求。

**Comment by urlesistiana** [comment]
自动附加客户端地址至 ecs 比较繁琐。mosdns v4 处理的并不好。v5 不打算造个方形的轮子。

既然已经部署至公网服务器了。建议前置 unbound 等专业软件处理 ecs。功能更多性能更好。
