### ISSUE TITLE
[Feature request]关于v5的cache插件的逻辑的疑问

### ISSUE THREAD

**Issue by wangmice** [IrineSistiana/mosdns#600]
**希望添加的功能**
是不是移除了when_hit这样的功能？

wiki里是这样描述的：
`如果请求命中缓存，则将缓存的应答放入请求。
当某一请求经过 cache 后，cache 会在这个请求处理流程结束时自动将应答放入缓存。用户无需介入。`
如果一个请求被缓存命中，那后续的插件还会继续运行吗？是直接按缓存应答还是直到后续流程结束再返回？这样缓存没起到加速的功能吧？
如果命中后直接应答的话，希望能加入when_hit这个功能，比如后续可以执行ipset或nftset的功能。

**Comment by urlesistiana** [comment]
v5 只会生成应答，不会自动返回，需要手动返回。就是为了能更好的配合ipset和nftset。

https://github.com/IrineSistiana/mosdns/discussions/562#discussioncomment-4676699

**Comment by wangmice** [comment]
> v5 只会生成应答，不会自动返回，需要手动返回。就是为了能更好的配合ipset和nftset。
> 
> [#562 (comment)](https://github.com/IrineSistiana/mosdns/discussions/562#discussioncomment-4676699)
怎么判断命中了缓存然后返回呢？
