### ISSUE TITLE
关于静态编译的问题？

### ISSUE THREAD

**Issue by swordsmile** [IrineSistiana/mosdns#61]
目前我个人情况是使用 OpenWrt X86 软路由，发现 mosdns 很好用，已经替换 dnsmasq 了。今天在升级版本的时候发现使用不了，经排查发现是动态链接的问题。

由于 OpenWrt Alpine 这种 Linux 系统采用 MUSL 动态库，所以导致动态链接的最新版本 v1.3.2 无法运行。
以 linux amd64 为例，我看了下包里动态链接的文件有 19M，我自行静态编译的才 15M。

我编译的命令如下：
`env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.version=v1.3.2" -trimpath -o mosdns`

**Comment by IrineSistiana** [comment]
感谢反馈. 换用 Action 编译的时候, 忘记设 CGO_ENABLED=0了.
