### ISSUE TITLE
[Feature request]能否添加Age18+的过滤模块

### ISSUE THREAD

**Issue by cqjerry** [IrineSistiana/mosdns#617]
**希望添加的功能**

能否添加Age18+的rule list功能（类似DNS广告过滤模块），
目前在用adguard + mosdns，但其实adguard仅使用了其屏蔽成人内容的功能，
如果mosdns可集成该列表，那完全可取代adguard。

**Comment by urlesistiana** [comment]
mosdns 可以做到这个。见 wiki。

mosdns不会集成任何列表。用什么列表由用户决定。
