### ISSUE TITLE
[Feature request] 建议 cache 插件的 查询 与 写入 能分开控制。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [IrineSistiana/mosdns#620]
### 希望添加的功能

目前  cache 插件是自动工作的，不够灵活。

 比如一般来说 cache 插件 都要放在流程前部，匹配后就跳出流程，已提高效率，
但如果一个域名列表想跳过 cache 插件，就必须放在  cache 插件之前。

以典型的国内外分流场景来说，多数是国内查询，少部分是国外查询。
 而国外查询经常有特殊的要求，希望跳过 cache 插件，就要放在 cache 插件之前，
每次查询都要检索一次域名列表，非常浪费性能。

 我的想法是把 cache 插件的 查询指令 和 写入指令 分开。
用户创建每个 cache  配置时，搞两个子标签（tag:），分别搞对应 查询和写入 。
比如 
```
tag: "abc_cache"
type: "cache"
args:
 read_cache_tag:"read_abc_cache"
 write_cache_tag:"write_abc_cache"
 ......
```

这样查询和写入指令，都可以放在最恰当的地方，减少多余流程，提高性能。
也为多个 cache 插件共用的情况，减少数据干扰，降低配置复杂度。

希望开发者能实现😁

几个想法

- 对于目前 cache 插件的自动模式，建议放弃，还能减少麻烦。反正大家也习惯改语法了🤪
- cache 插件 内部同一种子标签，我觉得可以有多个，功能一样，可理解为别名，用来在日志中识别。
- 目前 sequence ，返回查询和结束流程是一体的，也许也可以分开。

**Comment by fangjia052** [comment]
+1

**Comment by urlesistiana** [comment]
> 每次查询都要检索一次域名列表，非常浪费性能。

不会，检索域名表非常高效无论几百万域名也几乎不要性能。除非域名表里有正则表达式。

> 我的想法是把 cache 插件的 查询指令 和 写入指令 分开。

什么场景下需要分开执行呢？能举个例子或者写个流程么？

**Comment by wy16W2pIilK1xgqN** [comment]
> > 每次查询都要检索一次域名列表，非常浪费性能。
> 
> 不会，检索域名表非常高效无论几百万域名也几乎不要性能。除非域名表里有正则表达式。
> 
> > 我的想法是把 cache 插件的 查询指令 和 写入指令 分开。
> 
> 什么场景下需要分开执行呢？能举个例子或者写个流程么？

我的想法有个预设前提，就是在 cache 缓存中查找，比检索域名列表快。

比如前面说的，国内外分流场景。
如果希望国内外有不同 cache  策略，就需要先检索 域名列表进行分流。
如果分开 cache 查询和写入指令，就可以在开头放多个 cache 查询指令，
全查询不上时再用域名列表分流，上游查询到之后在写入指定的cache。



总而言之，多查 cache ，少查域名列表。

**Comment by urlesistiana** [comment]
性能上不用担心查找。除了域名表里有正则表达式，其他地方查找都是 hashmap。O(1)。查 1000 次消耗的性能估计比不过发一个 udp 数据包的。
