### ISSUE TITLE
[Feature request] Specific TTL options for NXDOMAIN and empty responses (negative TTL)

### ISSUE THREAD

**Issue by alpominth** [IrineSistiana/mosdns#622]
### 希望添加的功能

Let's suppose I configured my cache in mosdns for holding the responses 7 days and I got a NXDOMAIN reponse for a site I use to browse in the Sunday, I could access the site only at the end of the week.

I think this is really important.

**Comment by urlesistiana** [comment]
Mosdns cache does not apply user configured cache ttl to negative responses. The negative cache ttl for nxdomian is hardcoded to 30s. 

I don't think it has to be configurable. Since most users don't needs this.

**Comment by alpominth** [comment]
Ok.
