### ISSUE TITLE
[Feature request]  恢复常规fallback

### ISSUE THREAD

**Issue by yubanmeiqin9048** [IrineSistiana/mosdns#638]
### 希望添加的功能

- ```常规 fallback: 监控主流水线最近 stat_length 次的请求状态，如果出现 threshold 次问题(没有应答或者有报错)，则下次请求会一并执行次流水线。取最先返回的应答。```

**Comment by urlesistiana** [comment]
v5之所以去掉。是因为”v4 常规 fallback“ 实际应用中并不好用。不如 快速 fallback。

你需要常规 fallback 的原因是什么？

**Comment by yubanmeiqin9048** [comment]
> v5之所以去掉。是因为”v4 常规 fallback“ 实际应用中并不好用。不如 快速 fallback。
> 
> 你需要常规 fallback 的原因是什么？

希望尽量不进secondary流程，将其作为一种“迫不得已”的手段，这点 常规fallback 可以实现

**Comment by urlesistiana** [comment]
> 希望尽量不进secondary流程，将其作为一种“迫不得已”的手段

这点快速 fallback 也可以。
