### ISSUE TITLE
[Feature request] hosts插件监控文件改动或提供命令重新加载hosts文件

### ISSUE THREAD

**Issue by xiaolei0125** [IrineSistiana/mosdns#64]
**希望添加的功能**
hosts插件能够监控hosts文件的改动，然后自动重新加载hosts文件的配置；
或让mosdns提供一个命令，在不重启mosdns服务的情况下，可以重新加载hosts文件。

**请详细描述一下该功能作用和使用场景**
像有些用户有修改自定义的域名到动态IP的场景；
例如，我运行了很多docker容器，我有把域名解析到容器IP的需求，但是容器的IP很可能重启后发现了变化， 我有脚本监控容器IP的变化然后将新的IP和预定义的域名写入hosts文件，  这样其他的应用总是可以正常的通过域名访问到容器提供的服务。

**Comment by IrineSistiana** [comment]
> 我有脚本监控容器IP的变化然后将新的IP和预定义的域名写入hosts文件

直接脚本 restart mosdns 不是更容易而且稳定么。我一直这么干。

**Comment by xiaolei0125** [comment]
> > 我有脚本监控容器IP的变化然后将新的IP和预定义的域名写入hosts文件
> 
> 直接脚本 restart mosdns 不是更容易而且稳定么。我一直这么干。

后来想想没有长连接，访问也不频繁， 重启耗时几秒钟应该影响也不大，好的，我先实际使用一段时间看看。

**Comment by IrineSistiana** [comment]
> 重启耗时几秒钟

你是不是导入了 dat 文件的数据。protobuf 读数据挺耗时间的因为要读所有分类的所有数据，包括没用的分类。

把数据换成文本，即使载入 10w 多的文本数据，也只要大概 100ms。

**Comment by xiaolei0125** [comment]
@IrineSistiana 感谢，修改之后，确实快多了，那重启来加载hosts就没什么问题了。  
不过hosts插件有个配置文件解析的问题，我另外提了一个issue,  麻烦你看看，谢谢了。
