### ISSUE TITLE
[Feature request]  mosdns的geo匹配规则是什么呢 

### ISSUE THREAD

**Issue by ilafz** [IrineSistiana/mosdns#640]
### 希望添加的功能

能否添加像v2rayN那样的匹配算法 
linear：使用线性匹配算法，
mph：使用最小完美散列（minimal perfect hash）算法
匹配速度提升约 30%，内存占用减少约 15%
来更快的匹配域名ip

**Comment by urlesistiana** [comment]
hash。wiki 里写的很清楚。
