### ISSUE TITLE
[Feature request] 增加HTTPS类型的DNS记录，以对抗SNI阻断

### ISSUE THREAD

**Issue by ZeppLu** [IrineSistiana/mosdns#644]
### 希望添加的功能
支持DNS中HTTPS类型（type==65）的查找。
相关RFC：https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/

### 动机
目前mosdns似乎只响应A和AAAA查询请求，可以理解为专职提供未受污染的IP
https://github.com/IrineSistiana/mosdns/blob/81fff0b6d6163f1003ea32b8eb58886c43e28009/pkg/hosts/hosts.go#L58-L60

但是众所周知，防火墙早已大规模应用SNI阻断，导致即使使用正确的、未受屏蔽的IP去连接网站，但还是会因为网站url在黑名单中而无法连接。针对这一问题，目前较有前景的解决方法是ECH，Encrypted Client Hello，其能够最大可能地隐藏网站域名，避免被防火墙探测到。

为了使用ECH，网站服务端需要在DNS的HTTPS类型记录中写入一个ech字段。但是目前mosdns没有正确回复HTTPS类型的请求，导致浏览器无法以ECH连接到网站。可将其与1.1.1.1对比：
```
~$ RRTYPE=HTTPS dnslookup tls-ech.dev https://example.mosdns/dns-query
dnslookup v. v1.8.1
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 27310
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;tls-ech.dev.   IN       HTTPS

;; AUTHORITY SECTION:
.       300     IN      SOA     fake-ns.mosdns.fake.root. fake-mbox.mosdns.fake.root. 2021110400 1800 900 604800 86400

~$ RRTYPE=HTTPS dnslookup tls-ech.dev https://cloudflare-dns.com/dns-query
dnslookup v. v1.8.1
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 59257
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;tls-ech.dev.   IN       HTTPS

;; ANSWER SECTION:
tls-ech.dev.    60      IN      HTTPS   1 . ech="AEn+DQBFKwAgACABWIHUGj4u+PIggYXcR5JF0gYk3dCRioBW8uJq9H4mKAAIAAEAAQABAANAEnB1YmxpYy50bHMtZWNoLmRldgAA"
```

**Comment by urlesistiana** [comment]
> 目前mosdns似乎只响应A和AAAA查询请求，可以理解为专职提供未受污染的IP

并不是。mosdns 可转发任何请求，不会主动的屏蔽/修改请求，除非用户设定了相关逻辑。貌似是你用了 reject 之类的操作把 https 类型请求屏蔽了。

**Comment by ZeppLu** [comment]
感谢，我看一下
