### ISSUE TITLE
是不是还没有支持中文域名的分流解析

### ISSUE THREAD

**Issue by aijwfsibari** [IrineSistiana/mosdns#655]
### 希望添加的功能

比如我在灰名单里添加 `domain:新华网.cn` ，查了记录发现 `新华网.cn` 还是走的本地DNS解析，没有走远程DNS解析

**Comment by kkkgo** [comment]
按照DNS标准，中文域名的解析都需要转成Punycode码。  
https://www.ymw.cn/whois/punycode.html
