### ISSUE TITLE
[BUG]动态插件报错：plugin: not implemented

### ISSUE THREAD

**Issue by mkanako** [IrineSistiana/mosdns#66]
`CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build --buildmode=plugin -ldflags "-s -w -X main.version=v1.3.4-0-gc51a109" -trimpath -o ./ping.so ./dispatcher/plugin/executable/ping/ping.go`

这样编译出来的插件加载报错plugin: not implemented

然后我看项目是发布是
https://github.com/IrineSistiana/mosdns/blob/cba7a29874501c5f388c16f2e32ff848541bbf07/.github/workflows/release.yml#L43

于是改成CGO_ENABLED=0，但编译又报错了loadinternal: cannot find runtime/cgo

然后我把项目clone下来，自己编译为CGO_ENABLED=1，这样插件就能正常加载

谷歌半天找到https://github.com/golang/go/issues/19569

无解了吗？

**Comment by IrineSistiana** [comment]
~既然你谷歌过了，你应该发现了 plugin 是个非常坑人的玩意了~

> 这样编译出来的插件加载报错plugin: not implemented

release 是故意 `CGO_ENABLED: '0' ` 的，一直都是，所以编译出来的二进制都是不能用 plugin 的。为什么？为了兼容性 #61。

> 然后我把项目clone下来，自己编译为CGO_ENABLED=1，这样插件就能正常加载

是的，如果想用 plugin，要求CGO_ENABLED=1，而且 mosdns 和 plugin 的编译环境也要一模一样。也就是说 golang 版本要一样，依赖的代码要一样，gcflag 和 GCC 也要一样。

所以用 plugin 最好的方法就是自己编译.....

**Comment by IrineSistiana** [comment]
其实 plugin 我自己都不用了，实在是难用，不能跨平台......

还是直接 import 编译在一起方便。

**Comment by mkanako** [comment]
之所以用动态插件，是因为我不想去动项目源码，直接用你发布的二进制，不用自己维护更新拉代码在自己编译

那这样说的话动态插件其实很鸡肋，要我自己编译话，那我就没必要用动态插件
