### ISSUE TITLE
[BUG] ext：后的路径文件用引号包围则找不到路径

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mosdns#69]
**出现了什么问题**

ext：后的文件用引号包围则找不到路径，去掉引号后正常，这样的话如果路径或者文件名包含空格怎么处理？

```txt
failed to load file ext:"/root/cfg/geosite.dat:geolocation-!cn": open "/root/cfg/geosite.dat: no such file or directory
```

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：1.4.0

使用的启动参数或启动方式：

操作系统和平台：Linux

**Comment by IrineSistiana** [comment]
ext: 不是键，是字符串的一部分 要一并扩，"ext:xxxxxx.file"

: 容易产误解......

**Comment by rampageX** [comment]
O~
