### ISSUE TITLE
配置文件兼容问题

### ISSUE THREAD

**Issue by vrichv** [IrineSistiana/mosdns#7]
希望配置文件不兼容的话，希望大版本号能够变更，这样能避免很多麻烦。
0.x.x -->配置不兼容-->1.x.x
版本号大又不是没有先例，比如nvidia，chrome这些版本帝

**Comment by IrineSistiana** [comment]
0.xx 一般代表还在开发。不兼容很正常。

还有就是 go 程序很少刷大版本号。因为依赖问题可能让人头疼。一般都刷二级版本号。比如 adhome 都刷到 0.一百多了。

**Comment by delphinuz** [comment]
建议里面放个基本功能(像是已有dns分流)的 config.yaml，使用者下载后可直接使用。
