### ISSUE TITLE
[BUG]mosdns.exe打不开

### ISSUE THREAD

**Issue by chinaniupai** [IrineSistiana/mosdns#71]
mosdns.exe打不开

**Comment by CCNano** [comment]
请阅读Wiki。。。。使用service_control.bat运行

**Comment by joingit-20** [comment]
win7用管理员运行,提示还不是管理员,是怎么回事,

**Comment by chinaniupai** [comment]
@Nanonona 没用，运行不了。提示服务开启失败

**Comment by chinaniupai** [comment]
@Nanonona 而且无法打开百度等网站，感觉就是启动失败

**Comment by CCNano** [comment]
开发者只提供了amd64程序，只支持64位操作系统，你看一下系统是多少位的

**Comment by CCNano** [comment]
[mosdns.zip](https://github.com/IrineSistiana/mosdns/files/6033484/mosdns.zip)

这是我配置的可以正常使用的，出问题可以打开log.log查看问题，可以把内容发上来方便查看问题
![image](https://user-images.githubusercontent.com/48090953/108950090-9b765300-76a0-11eb-840c-18f9256681f2.png)

**Comment by chinaniupai** [comment]
> 开发者只提供了amd64程序，只支持64位操作系统，你看一下系统是多少位的

我的系统是64的，谢谢啦我打开看下

**Comment by chinaniupai** [comment]
> > 开发者只提供了amd64程序，只支持64位操作系统，你看一下系统是多少位的
> 
> 我的系统是64的，谢谢啦我打开看下

我的天，你的配置我能正常用了，谢谢您啊，太感谢了，请问您这个配置主要功能针对的是什么呀？
针对的是自动分流国内国外域名走哪个DNS的防污染功能的吗？

**Comment by chinaniupai** [comment]
> [mosdns.zip](https://github.com/IrineSistiana/mosdns/files/6033484/mosdns.zip)
> 
> 这是我配置的可以正常使用的，出问题可以打开log.log查看问题，可以把内容发上来方便查看问题
> ![image](https://user-images.githubusercontent.com/48090953/108950090-9b765300-76a0-11eb-840c-18f9256681f2.png)

你的配置我可以正常使用了，谢谢您，请问为什么我用wiki配置示例里那个直接复制粘贴却无法使用？

就是
本地/远程域名分流外加广告域名屏蔽。这个配置示例使用了 V2Ray 路由规则文件加强版 的 IP 和域名资源。下载 geoip.dat 和 geosite.dat 文件到 mosdns 的目录后，该配置即可复制后直接使用。

**Comment by IrineSistiana** [comment]
@Nanonona 感谢提供参考。

有个小问题，`ecs.auto` 取客户端ip作为 ecs，这个选择是给部署在公网的服务器用的。

如果是本机自己部署自己用的话，附加的客户端ip是127.0.0.1，所以附加上的ecs没有意义。其实客户端不需要ecs，因为上游服务器都会自动处理你的ip。

**Comment by CCNano** [comment]
@IrineSistiana 好的，谢谢，ecs其实我也不是很懂

**Comment by CCNano** [comment]
@chinaniupai 我只做了国内外分流，开发者wiki里很详细，你可以自己配置需要的功能

**Comment by chinaniupai** [comment]
> @chinaniupai 我只做了国内外分流，开发者wiki里很详细，你可以自己配置需要的功能

我大概也只是想要一个防污染dns而已
