### ISSUE TITLE
希望自动更新数据库那能更新独立设置。

### ISSUE THREAD

**Issue by iamyangyiok** [IrineSistiana/mosdns#726]
### 希望添加的功能

现在更新广告规则和GEDATA是一同更新，且国内更新GEODATA经常失败，推测执行方式是先清掉GEODATA，再更新。因容易更新失败，先删除GEODATA库也导致PW分流失败，且科学中断，MOSDNS GEODATA也无法正常更新，造成循环冲突。所以我每次都只能更完更新广告后，再关了PW分流，让PW手工再更新下GEODATA，才正常。现在只好停用LUCI-MOSDNS的库更新。所以希望自动更新库那能独立勾选，广告、GEODATA可分别选择，当然如果GEODATA更新方式也优化下更好。（更新方式是我个人推断，如不准确，还望见谅，但确实我现使用是这样情况。），再次表示感谢，让MOSDNS更简单化。

**Comment by IrineSistiana** [comment]
反馈错地方了。

**Comment by mbicc** [comment]
> ### 希望添加的功能
> 现在更新广告规则和GEDATA是一同更新，且国内更新GEODATA经常失败，推测执行方式是先清掉GEODATA，再更新。因容易更新失败，先删除GEODATA库也导致PW分流失败，且科学中断，MOSDNS GEODATA也无法正常更新，造成循环冲突。所以我每次都只能更完更新广告后，再关了PW分流，让PW手工再更新下GEODATA，才正常。现在只好停用LUCI-MOSDNS的库更新。所以希望自动更新库那能独立勾选，广告、GEODATA可分别选择，当然如果GEODATA更新方式也优化下更好。（更新方式是我个人推断，如不准确，还望见谅，但确实我现使用是这样情况。），再次表示感谢，让MOSDNS更简单化。

相同的问题,我是mosdns+openclash.目前2个路由器都出现了外网打不开.搞半天不知道原因,后来关mosdns正常了,
都是mosdns更新失败了,导致外网不能解析.
现在手动设置mosdns,openclash 的计划任务时间,但是mosdns自带的去AD这个设置不了,除非手动修改sh文件

> 反馈错地方了。

楼主的意思就是mosdns使用的几个文件可以单独设置更新时间,一起更新容易失败.
