### ISSUE TITLE
能否考虑增加保持护程序。

### ISSUE THREAD

**Issue by iamyangyiok** [IrineSistiana/mosdns#727]
### 希望添加的功能

各类科学插件，或DNS插件因更新或改应用，有时会错误转移DNS接口的控制权，导致DNS错误更改或失效。从而想到，能否LUCI-MOSDNS有个守护DNS功能，就是轮询监测，测到解析DNS失败。就再强制再应用一次当前设置，拿回DNS控制权。这样网络稳定性得到了加强。还望考虑，再次感谢。

**Comment by IrineSistiana** [comment]
反馈错地方了。
