### ISSUE TITLE
[Feature request] 能否扩展 redirect 插件的功能，以实现 IP 匹配后插入 CNAME 重新查询？

### ISSUE THREAD

**Issue by cherinyy** [IrineSistiana/mosdns#739]
### 希望添加的功能

需求是关于 Cloudflare 优选 IP 的问题。

比如 `mirror.apad.pro` 本身就是 Cloudflare 优选 IP 网站，而 Cloudflare 公开了[自身的 IP 范围](https://www.cloudflare.com/ips/)。那么我们能否在匹配到 Cloudflare 的 IPv4 地址后，通过 redirect 插件插入 CNAME 至 `mirror.apad.pro` 然后重新查询？

**Comment by IrineSistiana** [comment]
`keyword: mirror.apad.pro` 。空 keyword 能匹配一切，注意": "后有空格。

然后在 redirect 前面设置 ip 条件。

**Comment by cherinyy** [comment]
好的谢谢！
