### ISSUE TITLE
[Feature request] v5能不能增加一个打乱返回IP的插件

### ISSUE THREAD

**Issue by wukecheng** [IrineSistiana/mosdns#740]
### 希望添加的功能

hosts,black_hole,和dns查询返回的结果有多个IP时能不能随机打乱?
我见V4上有相关的插件_misc_optm可以实现,V5呢?

**Comment by IrineSistiana** [comment]
打乱返回 IP 的作用是什么？

**Comment by wukecheng** [comment]
> 打乱返回 IP 的作用是什么？

可以实现故障切换和负载均衡啊,像cloudflare这种优选多ip的经常失效的,对于hosts和black_hole添加多IP的,只会使用第一个,添加多个的作用就变得没意义了,就拿ping来说,绑定了4个IP,手动把第一个IP改成错的,ping的话每次都是第一个错的IP,这种解析结果多IP域名变得没有意义了,还有passwall也是一样,总是固定返回使用第一个,第一个IP是错的话后面备用的IP就不能替补上去了,如果打乱的话,但遇到错的IP,再次解析还能选到对的IP上

**Comment by IrineSistiana** [comment]
> 可以实现故障切换和负载均衡

不是打乱 IP 就能实现的。

> 添加多个的作用就变得没意义

返回多个IP客户端需要自己故障切换和负载均衡。如果客户端不会，随机返回IP也不会有作用。

**Comment by miaomiaosoft** [comment]
> > 可以实现故障切换和负载均衡
> 
> 不是打乱 IP 就能实现的。
> 
> > 添加多个的作用就变得没意义
> 
> 返回多个IP客户端需要自己故障切换和负载均衡。如果客户端不会，随机返回IP也不会有作用。

他需要的功能可能是将多个IP结果在返回前先 ping 或 tcping 一遍，将延迟最低的排在第一位，类似smartdns。

**Comment by Canda15** [comment]
我来说一下我的用途吧。也是需要一个乱序，或者负载均衡这样的功能。
我有一个国外的VPS需要长期取国内的文件。即使使用smartdns 优选出2个最快的ip，那个软件多线程下载也只使用第一个ip，国外大流量访问一个IP会被QOS。如果这时候乱序或者负载均衡排序的话，就能让这两个IP都能用上，加快下载速度

**Comment by IrineSistiana** [comment]
> 我见V4上有相关的插件_misc_optm

> 如果这时候乱序或者负载均衡排序的话，就能让这两个IP都能用上，加快下载速度

v4 添加过这个功能，是因为当时有错觉，觉得有用。实际上没用。所以 v5 没有。

DNS 打乱 IP ≠ 全自动无感负载均衡。没这种好事。负载均衡需要软件自己实现。软件本身不支持，没有别的拯救办法。
