### ISSUE TITLE
[Bug] V5.3.1 数据库更新失败，提示“请检查网络状态”

### ISSUE THREAD

**Issue by landyxin** [IrineSistiana/mosdns#754]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [ ] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

V5.3.1

### 操作系统

x86-64

### Bug 描述和复现步骤

mosdns更新数据库失败，提示“检查网络状态”
但是网络环境没什么问题，可以翻墙，也可以正常上内网，什么原因？
<img width="476" alt="image" src="https://github.com/IrineSistiana/mosdns/assets/15067842/1e523687-ccc5-45e1-a69e-381707610225">

<img width="738" alt="image" src="https://github.com/IrineSistiana/mosdns/assets/15067842/ded716f0-32fe-46f3-8161-514ee1e99ad5">

### 使用的配置文件

```yaml
配置文件在哪呢？抱歉我不会
```

**Comment by Teacher-c** [comment]
same here
红米ax6 openwrt

**Comment by erj855** [comment]
我也存在同样的问题

**Comment by 13311031900** [comment]
root@iStoreOS:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://gh-proxy.com/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gh-proxy.com:443 
root@iStoreOS:~# /usr/share/mosdns/mosdns.sh geodata
Downloading https://ghps.cc/https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip-only-cn-private.dat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ghps.cc:443
