### ISSUE TITLE
[Feature request] 提供将lazy_cache写入内存的选项

### ISSUE THREAD

**Issue by notch1p** [IrineSistiana/mosdns#778]
### 希望添加的功能

对于一般的机器来说目前的lazy_cache是没有问题的。但是对于树莓派这种使用TF卡作为存储的单板机来说频繁写入容易降低寿命。希望能够增加一个小开关让用户选择是否将缓存写入内存，毕竟Pi 5有8G内存，不用用也挺浪费的。

*祝元旦快乐*

**Comment by likevi9528** [comment]
size: 1024
dump_interval: 600
调大这两个试试，或者关闭dump_file选项

**Comment by sbwml** [comment]
缓存本来就是在内存里，dump 只是让你重启服务时，可以从文件中重新读取缓存到内存里使用。如果考虑到存储器读写问题，只需要增加 dump 间隔

**Comment by notch1p** [comment]
原来如此。我还有一个小问题，内存中的缓存大小的管理应该是自动的吧？想说能不能手动指定占用大小，还是说其实没必要。

**Comment by sbwml** [comment]
它不是根据你设置来的吗    缓存条目数量

发自我的iPhone
