### ISSUE TITLE
[Bug] 启用Cloudflare 自选IP选项时会导致cloudflare tunnel连接失败

### ISSUE THREAD

**Issue by Pigeonszz** [IrineSistiana/mosdns#819]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.3.1

### 操作系统

OpenWrt

### Bug 描述和复现步骤

在OpenWrt的Luci-app页面开启Cloudflare直选IP选项，输入直选IP，如"104.18.170.22"，生效后刷新DNS缓存，cloudflared连接 i/o timeout ，关闭选项并刷新DNS缓存后恢复正常连接

### 使用的配置文件

```yaml
config mosdns 'config'
        option listen_port '5335'
        option geo_update_week_time '*'
        option redirect '1'
        option configfile '/var/etc/mosdns.json'
        option log_level 'info'
        option log_file '/var/log/mosdns.log'
        option lazy_cache_ttl '86400'
        option insecure_skip_verify '0'
        option custom_local_dns '1'
        option apple_optimization '1'
        list local_dns 'h3://dns.alidns.com/dns-query'
        list local_dns 'quic://dns.alidns.com'
        list local_dns 'https://dns.alidns.com/dns-query'
        list local_dns 'https://doh.pub/dns-query'
        list local_dns 'https://doh.360.cn/dns-query'
        option enable_pipeline '1'
        option enable_ecs_remote '1'
        option dump_file '1'
        option dump_interval '3600'
        option minimal_ttl '60'
        option maximum_ttl '600'
        option listen_port_api '9090'
        option geo_auto_update '1'
        option geo_update_day_time '12'
        option concurrent '3'
        option bootstrap_dns '223.5.5.5'
        option adblock '0'
        option dns_leak '1'
        option cache_size '900000000'
        option idle_timeout '300'
        option enabled '1'
        list remote_dns 'https://cloudflare-dns.com/dns-query'
        list remote_dns 'https://1.1.1.1/dns-query'
        list remote_dns 'https://1.0.0.1/dns-query'
        option github_proxy 'https://gh-proxy.com'
        option custom_stream_media_dns '0'
        option prefer_ipv4 '1'
        list cloudflare_ip '104.18.170.22'
        option cloudflare '1
```

**Comment by Pigeonszz** [comment]
经检查应该是cloudflared查询的cfargotunnel.com（大概是这个域名？）被返回自选IP，但自选IP所属的服务器并没有运行argotunnel服务，导致cloudflared连不上
晚一点抓个包看一下

**Comment by Pigeonszz** [comment]
不仅仅是Cloudflare Tunnel，在访问如[letsencrypt](https://acme-v02.api.letsencrypt.org/directory)的有单独Cloudflare IP进行代理的都会出错

**Comment by xueba0458** [comment]
@Pigeonszz 不建议使用这个功能，因为cloudflare提供的ip文件包含的是所有的ip地址，包括某些付费的ip地址（如果你优选到了付费的ip地址，那使用免费的cloudflare大概率会无法访问）！

如果你非要使用这个功能，那建议你还是维护一个自己的ip库。抛开安全不谈也可以试试使用反代cf的ip地址😜😜

cloudflared argotunnel的ip地址是独立的....如果你只是想解决cloudflared argotunnel的问题，手动指定region1.v2.argotunnel.com和region2.v2.argotunnel.com的A记录就行了（去itdog查一下dns记录全部复制就可以了，就几个ip）

“经检查应该是cloudflared查询的cftunnel.com（大概是这个域名？）被返回自选IP” 
这个结论好像是错误的，cloudflared argotunnel会通过cftunnel.com进行连接而这个域名本身并没有解析记录，所以cloudflared会先通过另外的两个域名(region1.v2.argotunnel.com和region2.v2.argotunnel.com)查询ip地址再通过cfargotunnel.com的SNI进行连接！我之前也遇到过这个问题，我当时找了好久才发现是我DNS的问题...😢😢😢

ps：cloudflare tunnel使用的ipv4地址：198.41.192.77,198.41.192.67,198.41.192.7,198.41.192.47,198.41.192.37,198.41.192.27,198.41.192.227,198.41.192.167,198.41.192.57,198.41.192.107
cloudflare tunnel使用的ipv6地址：2606:4700:a0::9,2606:4700:a0::2,2606:4700:a0::4,2606:4700:a0::5,2606:4700:a0::3,2606:4700:a0::8,2606:4700:a0::1,2606:4700:a0::7,2606:4700:a0::6,2606:4700:a0::10

**Comment by RookieTerry** [comment]
> @Pigeonszz 不建议使用这个功能，因为cloudflare提供的ip文件包含的是所有的ip地址，包括某些付费的ip地址（如果你优选到了付费的ip地址，那使用免费的cloudflare大概率会无法访问）！
> 
> 如果你非要使用这个功能，那建议你还是维护一个自己的ip库。抛开安全不谈也可以试试使用反代cf的ip地址😜😜
> 
> cloudflared argotunnel的ip地址是独立的....如果你只是想解决cloudflared argotunnel的问题，手动指定region1.v2.argotunnel.com和region2.v2.argotunnel.com的A记录就行了（去itdog查一下dns记录全部复制就可以了，就几个ip）
> 
> “经检查应该是cloudflared查询的cftunnel.com（大概是这个域名？）被返回自选IP” 这个结论好像是错误的，cloudflared argotunnel会通过cftunnel.com进行连接而这个域名本身并没有解析记录，所以cloudflared会先通过另外的两个域名(region1.v2.argotunnel.com和region2.v2.argotunnel.com)查询ip地址再通过cfargotunnel.com的SNI进行连接！我之前也遇到过这个问题，我当时找了好久才发现是我DNS的问题...😢😢😢
> 
> ps：cloudflare tunnel使用的ipv4地址：198.41.192.77,198.41.192.67,198.41.192.7,198.41.192.47,198.41.192.37,198.41.192.27,198.41.192.227,198.41.192.167,198.41.192.57,198.41.192.107 cloudflare tunnel使用的ipv6地址：2606:4700:a0::9,2606:4700:a0::2,2606:4700:a0::4,2606:4700:a0::5,2606:4700:a0::3,2606:4700:a0::8,2606:4700:a0::1,2606:4700:a0::7,2606:4700:a0::6,2606:4700:a0::10

所以说cloudflare argo tunnel应该怎么样优选IP？[这个工具](https://github.com/XIU2/CloudflareSpeedTest)优选出来的IP有些不太行

**Comment by xueba0458** [comment]
> > @Pigeonszz 不建议使用这个功能，因为cloudflare提供的ip文件包含的是所有的ip地址，包括某些付费的ip地址（如果你优选到了付费的ip地址，那使用免费的cloudflare大概率会无法访问）！
> > 
> > 如果你非要使用这个功能，那建议你还是维护一个自己的ip库。抛开安全不谈也可以试试使用反代cf的ip地址😜😜
> > 
> > cloudflared argotunnel的ip地址是独立的....如果你只是想解决cloudflared argotunnel的问题，手动指定region1.v2.argotunnel.com和region2.v2.argotunnel.com的A记录就行了（去itdog查一下dns记录全部复制就可以了，就几个ip）
> > 
> > “经检查应该是cloudflared查询的cftunnel.com（大概是这个域名？）被返回自选IP” 这个结论好像是错误的，cloudflared argotunnel会通过cftunnel.com进行连接而这个域名本身并没有解析记录，所以cloudflared会先通过另外的两个域名(region1.v2.argotunnel.com和region2.v2.argotunnel.com)查询ip地址再通过cfargotunnel.com的SNI进行连接！我之前也遇到过这个问题，我当时找了好久才发现是我DNS的问题...😢😢😢
> > 
> > ps：cloudflare tunnel使用的ipv4地址：198.41.192.77,198.41.192.67,198.41.192.7,198.41.192.47,198.41.192.37,198.41.192.27,198.41.192.227,198.41.192.167,198.41.192.57,198.41.192.107 cloudflare tunnel使用的ipv6地址：2606:4700:a0::9,2606:4700:a0::2,2606:4700:a0::4,2606:4700:a0::5,2606:4700:a0::3,2606:4700:a0::8,2606:4700:a0::1,2606:4700:a0::7,2606:4700:a0::6,2606:4700:a0::10
> 
> 所以说cloudflare argo tunnel应该怎么样优选IP？[这个工具](https://github.com/XIU2/CloudflareSpeedTest)优选出来的IP有些不太行

没法优选……一共就只有几个ip……tunnel的ip是单独划分的，跟cdn服务是完全隔离的！！！如果你想要使用proxyip加速也不行，我亲自测试过，因为tunnel用的是非标端口(具体是哪个端口我忘了）……
唯一的办法就是，通过套一层速度还可以的科学上网节点来加速，或者买一台vps反代tunnel的ip……

**Comment by RookieTerry** [comment]
> > > @Pigeonszz 不建议使用这个功能，因为cloudflare提供的ip文件包含的是所有的ip地址，包括某些付费的ip地址（如果你优选到了付费的ip地址，那使用免费的cloudflare大概率会无法访问）！
> > > 如果你非要使用这个功能，那建议你还是维护一个自己的ip库。抛开安全不谈也可以试试使用反代cf的ip地址😜😜
> > > cloudflared argotunnel的ip地址是独立的....如果你只是想解决cloudflared argotunnel的问题，手动指定region1.v2.argotunnel.com和region2.v2.argotunnel.com的A记录就行了（去itdog查一下dns记录全部复制就可以了，就几个ip）
> > > “经检查应该是cloudflared查询的cftunnel.com（大概是这个域名？）被返回自选IP” 这个结论好像是错误的，cloudflared argotunnel会通过cftunnel.com进行连接而这个域名本身并没有解析记录，所以cloudflared会先通过另外的两个域名(region1.v2.argotunnel.com和region2.v2.argotunnel.com)查询ip地址再通过cfargotunnel.com的SNI进行连接！我之前也遇到过这个问题，我当时找了好久才发现是我DNS的问题...😢😢😢
> > > ps：cloudflare tunnel使用的ipv4地址：198.41.192.77,198.41.192.67,198.41.192.7,198.41.192.47,198.41.192.37,198.41.192.27,198.41.192.227,198.41.192.167,198.41.192.57,198.41.192.107 cloudflare tunnel使用的ipv6地址：2606:4700:a0::9,2606:4700:a0::2,2606:4700:a0::4,2606:4700:a0::5,2606:4700:a0::3,2606:4700:a0::8,2606:4700:a0::1,2606:4700:a0::7,2606:4700:a0::6,2606:4700:a0::10
> > 
> > 
> > 所以说cloudflare argo tunnel应该怎么样优选IP？[这个工具](https://github.com/XIU2/CloudflareSpeedTest)优选出来的IP有些连不上
> 
> 没法优选……一共就只有几个ip……tunnel的ip是单独划分的，跟cdn服务是完全隔离的！！！如果你想要使用proxyip加速也不行，我亲自测试过，因为tunnel用的是非标端口(具体是哪个端口我忘了）…… 唯一的办法就是，通过套一层速度还可以的科学上网节点来加速，或者买一台vps反代tunnel的ip……

好的，感谢回复！看来只能用机场节点或自建节点链式代理了。如果在自建节点的vps上安装frp反代cf tunnel，是不是也可以加速呢？

**Comment by xueba0458** [comment]
> > > > @Pigeonszz 不建议使用这个功能，因为cloudflare提供的ip文件包含的是所有的ip地址，包括某些付费的ip地址（如果你优选到了付费的ip地址，那使用免费的cloudflare大概率会无法访问）！
> > > > 如果你非要使用这个功能，那建议你还是维护一个自己的ip库。抛开安全不谈也可以试试使用反代cf的ip地址😜😜
> > > > cloudflared argotunnel的ip地址是独立的....如果你只是想解决cloudflared argotunnel的问题，手动指定region1.v2.argotunnel.com和region2.v2.argotunnel.com的A记录就行了（去itdog查一下dns记录全部复制就可以了，就几个ip）
> > > > “经检查应该是cloudflared查询的cftunnel.com（大概是这个域名？）被返回自选IP” 这个结论好像是错误的，cloudflared argotunnel会通过cftunnel.com进行连接而这个域名本身并没有解析记录，所以cloudflared会先通过另外的两个域名(region1.v2.argotunnel.com和region2.v2.argotunnel.com)查询ip地址再通过cfargotunnel.com的SNI进行连接！我之前也遇到过这个问题，我当时找了好久才发现是我DNS的问题...😢😢😢
> > > > ps：cloudflare tunnel使用的ipv4地址：198.41.192.77,198.41.192.67,198.41.192.7,198.41.192.47,198.41.192.37,198.41.192.27,198.41.192.227,198.41.192.167,198.41.192.57,198.41.192.107 cloudflare tunnel使用的ipv6地址：2606:4700:a0::9,2606:4700:a0::2,2606:4700:a0::4,2606:4700:a0::5,2606:4700:a0::3,2606:4700:a0::8,2606:4700:a0::1,2606:4700:a0::7,2606:4700:a0::6,2606:4700:a0::10
> > > 
> > > 
> > > 所以说cloudflare argo tunnel应该怎么样优选IP？[这个工具](https://github.com/XIU2/CloudflareSpeedTest)优选出来的IP有些连不上
> > 
> > 没法优选……一共就只有几个ip……tunnel的ip是单独划分的，跟cdn服务是完全隔离的！！！如果你想要使用proxyip加速也不行，我亲自测试过，因为tunnel用的是非标端口(具体是哪个端口我忘了）…… 唯一的办法就是，通过套一层速度还可以的科学上网节点来加速，或者买一台vps反代tunnel的ip……
> 
> 好的，感谢回复！看来只能用机场节点或自建节点链式代理了。如果在自建节点的vps上安装frp反代cf tunnel，是不是也可以加速呢？

你都有自己的vps了，直接用frp内网穿透不就行了！！！我测试下来，使用香港中转节点加速tunnel http2，效果其实并不明显……毕竟cloudflare在大陆的访问速度你懂的，而且没办法使用优选cname优化大陆用户的体验！！！
