### ISSUE TITLE
[Feature request] Cloudflare自选IP能否添加白名单功能

### ISSUE THREAD

**Issue by rumianoesa** [IrineSistiana/mosdns#849]
### 希望添加的功能

Cloudflare自选IP能否添加白名单功能，让不想使用自选IP的域名使用原本的解析结果，例如证书签署域名acme-v02.api.letsencrypt.org
尝试了将acme-v02.api.letsencrypt.org加入白名单和hosts都没有效果，会被Cloudflare自选IP覆盖

**Comment by rumianoesa** [comment]
目前采用的临时解决办法是在openwrt的/etc/config/dhcp添加
list server '/acme-v02.api.letsencrypt.org/223.5.5.5'
指定一条比mosdns优先级更高的转发
但是mosdns启动时会覆盖这条设置

**Comment by miaomiaosoft** [comment]
- tag: main
    type: sequence
    args:
      exec:
        - hosts
        - cache

        - if: query_TOP
          exec:
            - forward_UDP
            - _return
            
        - forward_UDP2


增加个 query_TOP 白名单域名规则，匹配后用 forward_UDP 解析并直接返回结果
没有匹配的走 forward_UDP2
这是 4.X 版本，5.X应该差不多的逻辑

**Comment by rumianoesa** [comment]
发错地方了，我用的是luci-app-mosdns的预设配置
