### ISSUE TITLE
[BUG] 使用一段时间会出现错误

### ISSUE THREAD

**Issue by delphinuz** [IrineSistiana/mosdns#9]
time="2020-12-xxTxx:xx:xx+08:00" level=warning msg="[{weixin.qq.com. 1 1}], from: 127.0.0.1:49460: query failed: plugin sequence_bypass_local reports an err: context deadline exceeded"

会出现这样的错误。

**Comment by IrineSistiana** [comment]
不按要求反馈的 issue 会被直接关掉。
