### ISSUE TITLE
可否编译一个MIPS的版本

### ISSUE THREAD

**Issue by cutemanworking** [IrineSistiana/mosdns#90]
想跑在MT7621A的openwrt环境，需要MIPS的版本，可否编译Release时加上这个版本? 感谢!!

**Comment by IrineSistiana** [comment]
有啊。MT7621A = mipsle softfloat。

**Comment by cutemanworking** [comment]
不好意思，前几天没时间重现问题。 

mipsle softfloat的版本在openwrt运行时报错: Segmentation fault

运行环境:
Newifi-D1 (CpuMark : 4942.542938 Scores)
OpenWrt R20.12.12 / LuCI Master (git-20.343.54716-6fc079f)

**Comment by IrineSistiana** [comment]
官方的 openwrt MT7621 的架构确实是 mipsle + softfloat。

openwrt 显示的完整架构是这个么 `MediaTek MT7621 ver:1 eco:3`

报 `Segmentation fault` 怕是内核加了什么黑科技导致不兼容了。或者你用 upx 了。
